// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: talon/v1/agents.proto

package talonv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/guygrigsby/talon/internal/api/v1/talon/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AgentsServiceName is the fully-qualified name of the AgentsService service.
	AgentsServiceName = "talon.v1.AgentsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AgentsServiceListProcedure is the fully-qualified name of the AgentsService's List RPC.
	AgentsServiceListProcedure = "/talon.v1.AgentsService/List"
	// AgentsServiceFilesListProcedure is the fully-qualified name of the AgentsService's FilesList RPC.
	AgentsServiceFilesListProcedure = "/talon.v1.AgentsService/FilesList"
	// AgentsServiceFilesGetProcedure is the fully-qualified name of the AgentsService's FilesGet RPC.
	AgentsServiceFilesGetProcedure = "/talon.v1.AgentsService/FilesGet"
	// AgentsServiceFilesSetProcedure is the fully-qualified name of the AgentsService's FilesSet RPC.
	AgentsServiceFilesSetProcedure = "/talon.v1.AgentsService/FilesSet"
	// AgentsServiceIdentityGetProcedure is the fully-qualified name of the AgentsService's IdentityGet
	// RPC.
	AgentsServiceIdentityGetProcedure = "/talon.v1.AgentsService/IdentityGet"
	// AgentsServiceSkillsStatusProcedure is the fully-qualified name of the AgentsService's
	// SkillsStatus RPC.
	AgentsServiceSkillsStatusProcedure = "/talon.v1.AgentsService/SkillsStatus"
	// AgentsServiceMemoryAppendProcedure is the fully-qualified name of the AgentsService's
	// MemoryAppend RPC.
	AgentsServiceMemoryAppendProcedure = "/talon.v1.AgentsService/MemoryAppend"
)

// AgentsServiceClient is a client for the talon.v1.AgentsService service.
type AgentsServiceClient interface {
	// List returns one row per configured agent (id, name,
	// workspace, model resolution).
	List(context.Context, *connect.Request[v1.Empty]) (*connect.Response[v1.JSONPayload], error)
	// FilesList enumerates the canonical per-agent files (system
	// prompt, auth-profiles, identity).
	FilesList(context.Context, *connect.Request[v1.AgentFilesListRequest]) (*connect.Response[v1.JSONPayload], error)
	// FilesGet returns the content of one per-agent file.
	FilesGet(context.Context, *connect.Request[v1.AgentFilesGetRequest]) (*connect.Response[v1.JSONPayload], error)
	// FilesSet writes the content of one per-agent file (talon
	// overlay only; openclaw layer is read-only).
	FilesSet(context.Context, *connect.Request[v1.AgentFilesSetRequest]) (*connect.Response[v1.Empty], error)
	// IdentityGet returns the agent's resolved identity (operator
	// token + device pairing context for channel routing).
	IdentityGet(context.Context, *connect.Request[v1.AgentIdentityGetRequest]) (*connect.Response[v1.JSONPayload], error)
	// SkillsStatus reports per-agent skill bindings + status.
	SkillsStatus(context.Context, *connect.Request[v1.SkillsStatusRequest]) (*connect.Response[v1.JSONPayload], error)
	// MemoryAppend records a memory entry for an agent (legacy
	// path — talon-2dn's jess/memory sidecar exposes the modern
	// "remember" tool to the model instead).
	MemoryAppend(context.Context, *connect.Request[v1.MemoryAppendRequest]) (*connect.Response[v1.Empty], error)
}

// NewAgentsServiceClient constructs a client for the talon.v1.AgentsService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAgentsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AgentsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	agentsServiceMethods := v1.File_talon_v1_agents_proto.Services().ByName("AgentsService").Methods()
	return &agentsServiceClient{
		list: connect.NewClient[v1.Empty, v1.JSONPayload](
			httpClient,
			baseURL+AgentsServiceListProcedure,
			connect.WithSchema(agentsServiceMethods.ByName("List")),
			connect.WithClientOptions(opts...),
		),
		filesList: connect.NewClient[v1.AgentFilesListRequest, v1.JSONPayload](
			httpClient,
			baseURL+AgentsServiceFilesListProcedure,
			connect.WithSchema(agentsServiceMethods.ByName("FilesList")),
			connect.WithClientOptions(opts...),
		),
		filesGet: connect.NewClient[v1.AgentFilesGetRequest, v1.JSONPayload](
			httpClient,
			baseURL+AgentsServiceFilesGetProcedure,
			connect.WithSchema(agentsServiceMethods.ByName("FilesGet")),
			connect.WithClientOptions(opts...),
		),
		filesSet: connect.NewClient[v1.AgentFilesSetRequest, v1.Empty](
			httpClient,
			baseURL+AgentsServiceFilesSetProcedure,
			connect.WithSchema(agentsServiceMethods.ByName("FilesSet")),
			connect.WithClientOptions(opts...),
		),
		identityGet: connect.NewClient[v1.AgentIdentityGetRequest, v1.JSONPayload](
			httpClient,
			baseURL+AgentsServiceIdentityGetProcedure,
			connect.WithSchema(agentsServiceMethods.ByName("IdentityGet")),
			connect.WithClientOptions(opts...),
		),
		skillsStatus: connect.NewClient[v1.SkillsStatusRequest, v1.JSONPayload](
			httpClient,
			baseURL+AgentsServiceSkillsStatusProcedure,
			connect.WithSchema(agentsServiceMethods.ByName("SkillsStatus")),
			connect.WithClientOptions(opts...),
		),
		memoryAppend: connect.NewClient[v1.MemoryAppendRequest, v1.Empty](
			httpClient,
			baseURL+AgentsServiceMemoryAppendProcedure,
			connect.WithSchema(agentsServiceMethods.ByName("MemoryAppend")),
			connect.WithClientOptions(opts...),
		),
	}
}

// agentsServiceClient implements AgentsServiceClient.
type agentsServiceClient struct {
	list         *connect.Client[v1.Empty, v1.JSONPayload]
	filesList    *connect.Client[v1.AgentFilesListRequest, v1.JSONPayload]
	filesGet     *connect.Client[v1.AgentFilesGetRequest, v1.JSONPayload]
	filesSet     *connect.Client[v1.AgentFilesSetRequest, v1.Empty]
	identityGet  *connect.Client[v1.AgentIdentityGetRequest, v1.JSONPayload]
	skillsStatus *connect.Client[v1.SkillsStatusRequest, v1.JSONPayload]
	memoryAppend *connect.Client[v1.MemoryAppendRequest, v1.Empty]
}

// List calls talon.v1.AgentsService.List.
func (c *agentsServiceClient) List(ctx context.Context, req *connect.Request[v1.Empty]) (*connect.Response[v1.JSONPayload], error) {
	return c.list.CallUnary(ctx, req)
}

// FilesList calls talon.v1.AgentsService.FilesList.
func (c *agentsServiceClient) FilesList(ctx context.Context, req *connect.Request[v1.AgentFilesListRequest]) (*connect.Response[v1.JSONPayload], error) {
	return c.filesList.CallUnary(ctx, req)
}

// FilesGet calls talon.v1.AgentsService.FilesGet.
func (c *agentsServiceClient) FilesGet(ctx context.Context, req *connect.Request[v1.AgentFilesGetRequest]) (*connect.Response[v1.JSONPayload], error) {
	return c.filesGet.CallUnary(ctx, req)
}

// FilesSet calls talon.v1.AgentsService.FilesSet.
func (c *agentsServiceClient) FilesSet(ctx context.Context, req *connect.Request[v1.AgentFilesSetRequest]) (*connect.Response[v1.Empty], error) {
	return c.filesSet.CallUnary(ctx, req)
}

// IdentityGet calls talon.v1.AgentsService.IdentityGet.
func (c *agentsServiceClient) IdentityGet(ctx context.Context, req *connect.Request[v1.AgentIdentityGetRequest]) (*connect.Response[v1.JSONPayload], error) {
	return c.identityGet.CallUnary(ctx, req)
}

// SkillsStatus calls talon.v1.AgentsService.SkillsStatus.
func (c *agentsServiceClient) SkillsStatus(ctx context.Context, req *connect.Request[v1.SkillsStatusRequest]) (*connect.Response[v1.JSONPayload], error) {
	return c.skillsStatus.CallUnary(ctx, req)
}

// MemoryAppend calls talon.v1.AgentsService.MemoryAppend.
func (c *agentsServiceClient) MemoryAppend(ctx context.Context, req *connect.Request[v1.MemoryAppendRequest]) (*connect.Response[v1.Empty], error) {
	return c.memoryAppend.CallUnary(ctx, req)
}

// AgentsServiceHandler is an implementation of the talon.v1.AgentsService service.
type AgentsServiceHandler interface {
	// List returns one row per configured agent (id, name,
	// workspace, model resolution).
	List(context.Context, *connect.Request[v1.Empty]) (*connect.Response[v1.JSONPayload], error)
	// FilesList enumerates the canonical per-agent files (system
	// prompt, auth-profiles, identity).
	FilesList(context.Context, *connect.Request[v1.AgentFilesListRequest]) (*connect.Response[v1.JSONPayload], error)
	// FilesGet returns the content of one per-agent file.
	FilesGet(context.Context, *connect.Request[v1.AgentFilesGetRequest]) (*connect.Response[v1.JSONPayload], error)
	// FilesSet writes the content of one per-agent file (talon
	// overlay only; openclaw layer is read-only).
	FilesSet(context.Context, *connect.Request[v1.AgentFilesSetRequest]) (*connect.Response[v1.Empty], error)
	// IdentityGet returns the agent's resolved identity (operator
	// token + device pairing context for channel routing).
	IdentityGet(context.Context, *connect.Request[v1.AgentIdentityGetRequest]) (*connect.Response[v1.JSONPayload], error)
	// SkillsStatus reports per-agent skill bindings + status.
	SkillsStatus(context.Context, *connect.Request[v1.SkillsStatusRequest]) (*connect.Response[v1.JSONPayload], error)
	// MemoryAppend records a memory entry for an agent (legacy
	// path — talon-2dn's jess/memory sidecar exposes the modern
	// "remember" tool to the model instead).
	MemoryAppend(context.Context, *connect.Request[v1.MemoryAppendRequest]) (*connect.Response[v1.Empty], error)
}

// NewAgentsServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAgentsServiceHandler(svc AgentsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	agentsServiceMethods := v1.File_talon_v1_agents_proto.Services().ByName("AgentsService").Methods()
	agentsServiceListHandler := connect.NewUnaryHandler(
		AgentsServiceListProcedure,
		svc.List,
		connect.WithSchema(agentsServiceMethods.ByName("List")),
		connect.WithHandlerOptions(opts...),
	)
	agentsServiceFilesListHandler := connect.NewUnaryHandler(
		AgentsServiceFilesListProcedure,
		svc.FilesList,
		connect.WithSchema(agentsServiceMethods.ByName("FilesList")),
		connect.WithHandlerOptions(opts...),
	)
	agentsServiceFilesGetHandler := connect.NewUnaryHandler(
		AgentsServiceFilesGetProcedure,
		svc.FilesGet,
		connect.WithSchema(agentsServiceMethods.ByName("FilesGet")),
		connect.WithHandlerOptions(opts...),
	)
	agentsServiceFilesSetHandler := connect.NewUnaryHandler(
		AgentsServiceFilesSetProcedure,
		svc.FilesSet,
		connect.WithSchema(agentsServiceMethods.ByName("FilesSet")),
		connect.WithHandlerOptions(opts...),
	)
	agentsServiceIdentityGetHandler := connect.NewUnaryHandler(
		AgentsServiceIdentityGetProcedure,
		svc.IdentityGet,
		connect.WithSchema(agentsServiceMethods.ByName("IdentityGet")),
		connect.WithHandlerOptions(opts...),
	)
	agentsServiceSkillsStatusHandler := connect.NewUnaryHandler(
		AgentsServiceSkillsStatusProcedure,
		svc.SkillsStatus,
		connect.WithSchema(agentsServiceMethods.ByName("SkillsStatus")),
		connect.WithHandlerOptions(opts...),
	)
	agentsServiceMemoryAppendHandler := connect.NewUnaryHandler(
		AgentsServiceMemoryAppendProcedure,
		svc.MemoryAppend,
		connect.WithSchema(agentsServiceMethods.ByName("MemoryAppend")),
		connect.WithHandlerOptions(opts...),
	)
	return "/talon.v1.AgentsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AgentsServiceListProcedure:
			agentsServiceListHandler.ServeHTTP(w, r)
		case AgentsServiceFilesListProcedure:
			agentsServiceFilesListHandler.ServeHTTP(w, r)
		case AgentsServiceFilesGetProcedure:
			agentsServiceFilesGetHandler.ServeHTTP(w, r)
		case AgentsServiceFilesSetProcedure:
			agentsServiceFilesSetHandler.ServeHTTP(w, r)
		case AgentsServiceIdentityGetProcedure:
			agentsServiceIdentityGetHandler.ServeHTTP(w, r)
		case AgentsServiceSkillsStatusProcedure:
			agentsServiceSkillsStatusHandler.ServeHTTP(w, r)
		case AgentsServiceMemoryAppendProcedure:
			agentsServiceMemoryAppendHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAgentsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAgentsServiceHandler struct{}

func (UnimplementedAgentsServiceHandler) List(context.Context, *connect.Request[v1.Empty]) (*connect.Response[v1.JSONPayload], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("talon.v1.AgentsService.List is not implemented"))
}

func (UnimplementedAgentsServiceHandler) FilesList(context.Context, *connect.Request[v1.AgentFilesListRequest]) (*connect.Response[v1.JSONPayload], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("talon.v1.AgentsService.FilesList is not implemented"))
}

func (UnimplementedAgentsServiceHandler) FilesGet(context.Context, *connect.Request[v1.AgentFilesGetRequest]) (*connect.Response[v1.JSONPayload], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("talon.v1.AgentsService.FilesGet is not implemented"))
}

func (UnimplementedAgentsServiceHandler) FilesSet(context.Context, *connect.Request[v1.AgentFilesSetRequest]) (*connect.Response[v1.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("talon.v1.AgentsService.FilesSet is not implemented"))
}

func (UnimplementedAgentsServiceHandler) IdentityGet(context.Context, *connect.Request[v1.AgentIdentityGetRequest]) (*connect.Response[v1.JSONPayload], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("talon.v1.AgentsService.IdentityGet is not implemented"))
}

func (UnimplementedAgentsServiceHandler) SkillsStatus(context.Context, *connect.Request[v1.SkillsStatusRequest]) (*connect.Response[v1.JSONPayload], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("talon.v1.AgentsService.SkillsStatus is not implemented"))
}

func (UnimplementedAgentsServiceHandler) MemoryAppend(context.Context, *connect.Request[v1.MemoryAppendRequest]) (*connect.Response[v1.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("talon.v1.AgentsService.MemoryAppend is not implemented"))
}
