// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: talon/v1/channels.proto

package talonv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/guygrigsby/talon/internal/api/v1/talon/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ChannelsServiceName is the fully-qualified name of the ChannelsService service.
	ChannelsServiceName = "talon.v1.ChannelsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ChannelsServiceTelegramVerifyProcedure is the fully-qualified name of the ChannelsService's
	// TelegramVerify RPC.
	ChannelsServiceTelegramVerifyProcedure = "/talon.v1.ChannelsService/TelegramVerify"
	// ChannelsServiceTelegramCaptureSenderProcedure is the fully-qualified name of the
	// ChannelsService's TelegramCaptureSender RPC.
	ChannelsServiceTelegramCaptureSenderProcedure = "/talon.v1.ChannelsService/TelegramCaptureSender"
	// ChannelsServiceTelegramPersistProcedure is the fully-qualified name of the ChannelsService's
	// TelegramPersist RPC.
	ChannelsServiceTelegramPersistProcedure = "/talon.v1.ChannelsService/TelegramPersist"
)

// ChannelsServiceClient is a client for the talon.v1.ChannelsService service.
type ChannelsServiceClient interface {
	TelegramVerify(context.Context, *connect.Request[v1.TelegramVerifyRequest]) (*connect.Response[v1.JSONPayload], error)
	TelegramCaptureSender(context.Context, *connect.Request[v1.TelegramCaptureSenderRequest]) (*connect.Response[v1.JSONPayload], error)
	TelegramPersist(context.Context, *connect.Request[v1.TelegramPersistRequest]) (*connect.Response[v1.Empty], error)
}

// NewChannelsServiceClient constructs a client for the talon.v1.ChannelsService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewChannelsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ChannelsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	channelsServiceMethods := v1.File_talon_v1_channels_proto.Services().ByName("ChannelsService").Methods()
	return &channelsServiceClient{
		telegramVerify: connect.NewClient[v1.TelegramVerifyRequest, v1.JSONPayload](
			httpClient,
			baseURL+ChannelsServiceTelegramVerifyProcedure,
			connect.WithSchema(channelsServiceMethods.ByName("TelegramVerify")),
			connect.WithClientOptions(opts...),
		),
		telegramCaptureSender: connect.NewClient[v1.TelegramCaptureSenderRequest, v1.JSONPayload](
			httpClient,
			baseURL+ChannelsServiceTelegramCaptureSenderProcedure,
			connect.WithSchema(channelsServiceMethods.ByName("TelegramCaptureSender")),
			connect.WithClientOptions(opts...),
		),
		telegramPersist: connect.NewClient[v1.TelegramPersistRequest, v1.Empty](
			httpClient,
			baseURL+ChannelsServiceTelegramPersistProcedure,
			connect.WithSchema(channelsServiceMethods.ByName("TelegramPersist")),
			connect.WithClientOptions(opts...),
		),
	}
}

// channelsServiceClient implements ChannelsServiceClient.
type channelsServiceClient struct {
	telegramVerify        *connect.Client[v1.TelegramVerifyRequest, v1.JSONPayload]
	telegramCaptureSender *connect.Client[v1.TelegramCaptureSenderRequest, v1.JSONPayload]
	telegramPersist       *connect.Client[v1.TelegramPersistRequest, v1.Empty]
}

// TelegramVerify calls talon.v1.ChannelsService.TelegramVerify.
func (c *channelsServiceClient) TelegramVerify(ctx context.Context, req *connect.Request[v1.TelegramVerifyRequest]) (*connect.Response[v1.JSONPayload], error) {
	return c.telegramVerify.CallUnary(ctx, req)
}

// TelegramCaptureSender calls talon.v1.ChannelsService.TelegramCaptureSender.
func (c *channelsServiceClient) TelegramCaptureSender(ctx context.Context, req *connect.Request[v1.TelegramCaptureSenderRequest]) (*connect.Response[v1.JSONPayload], error) {
	return c.telegramCaptureSender.CallUnary(ctx, req)
}

// TelegramPersist calls talon.v1.ChannelsService.TelegramPersist.
func (c *channelsServiceClient) TelegramPersist(ctx context.Context, req *connect.Request[v1.TelegramPersistRequest]) (*connect.Response[v1.Empty], error) {
	return c.telegramPersist.CallUnary(ctx, req)
}

// ChannelsServiceHandler is an implementation of the talon.v1.ChannelsService service.
type ChannelsServiceHandler interface {
	TelegramVerify(context.Context, *connect.Request[v1.TelegramVerifyRequest]) (*connect.Response[v1.JSONPayload], error)
	TelegramCaptureSender(context.Context, *connect.Request[v1.TelegramCaptureSenderRequest]) (*connect.Response[v1.JSONPayload], error)
	TelegramPersist(context.Context, *connect.Request[v1.TelegramPersistRequest]) (*connect.Response[v1.Empty], error)
}

// NewChannelsServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewChannelsServiceHandler(svc ChannelsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	channelsServiceMethods := v1.File_talon_v1_channels_proto.Services().ByName("ChannelsService").Methods()
	channelsServiceTelegramVerifyHandler := connect.NewUnaryHandler(
		ChannelsServiceTelegramVerifyProcedure,
		svc.TelegramVerify,
		connect.WithSchema(channelsServiceMethods.ByName("TelegramVerify")),
		connect.WithHandlerOptions(opts...),
	)
	channelsServiceTelegramCaptureSenderHandler := connect.NewUnaryHandler(
		ChannelsServiceTelegramCaptureSenderProcedure,
		svc.TelegramCaptureSender,
		connect.WithSchema(channelsServiceMethods.ByName("TelegramCaptureSender")),
		connect.WithHandlerOptions(opts...),
	)
	channelsServiceTelegramPersistHandler := connect.NewUnaryHandler(
		ChannelsServiceTelegramPersistProcedure,
		svc.TelegramPersist,
		connect.WithSchema(channelsServiceMethods.ByName("TelegramPersist")),
		connect.WithHandlerOptions(opts...),
	)
	return "/talon.v1.ChannelsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ChannelsServiceTelegramVerifyProcedure:
			channelsServiceTelegramVerifyHandler.ServeHTTP(w, r)
		case ChannelsServiceTelegramCaptureSenderProcedure:
			channelsServiceTelegramCaptureSenderHandler.ServeHTTP(w, r)
		case ChannelsServiceTelegramPersistProcedure:
			channelsServiceTelegramPersistHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedChannelsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedChannelsServiceHandler struct{}

func (UnimplementedChannelsServiceHandler) TelegramVerify(context.Context, *connect.Request[v1.TelegramVerifyRequest]) (*connect.Response[v1.JSONPayload], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("talon.v1.ChannelsService.TelegramVerify is not implemented"))
}

func (UnimplementedChannelsServiceHandler) TelegramCaptureSender(context.Context, *connect.Request[v1.TelegramCaptureSenderRequest]) (*connect.Response[v1.JSONPayload], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("talon.v1.ChannelsService.TelegramCaptureSender is not implemented"))
}

func (UnimplementedChannelsServiceHandler) TelegramPersist(context.Context, *connect.Request[v1.TelegramPersistRequest]) (*connect.Response[v1.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("talon.v1.ChannelsService.TelegramPersist is not implemented"))
}
