// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: talon/v1/chat.proto

package talonv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/guygrigsby/talon/internal/api/v1/talon/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ChatServiceName is the fully-qualified name of the ChatService service.
	ChatServiceName = "talon.v1.ChatService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ChatServiceSendProcedure is the fully-qualified name of the ChatService's Send RPC.
	ChatServiceSendProcedure = "/talon.v1.ChatService/Send"
	// ChatServiceHistoryProcedure is the fully-qualified name of the ChatService's History RPC.
	ChatServiceHistoryProcedure = "/talon.v1.ChatService/History"
	// ChatServiceSubscribeProcedure is the fully-qualified name of the ChatService's Subscribe RPC.
	ChatServiceSubscribeProcedure = "/talon.v1.ChatService/Subscribe"
)

// ChatServiceClient is a client for the talon.v1.ChatService service.
type ChatServiceClient interface {
	// Send accepts a user turn and returns the run ID immediately.
	// Events for the run flow on Subscribe — keeping send and
	// subscribe separate matches the existing WS contract so
	// frontends migrate one call at a time.
	Send(context.Context, *connect.Request[v1.ChatSendRequest]) (*connect.Response[v1.ChatSendResponse], error)
	// History returns the recorded turns for a session.
	History(context.Context, *connect.Request[v1.ChatHistoryRequest]) (*connect.Response[v1.JSONPayload], error)
	// Subscribe opens a server-stream of chat events scoped to a
	// session. Filters by run when run_id is set.
	Subscribe(context.Context, *connect.Request[v1.ChatSubscribeRequest]) (*connect.ServerStreamForClient[v1.ChatEvent], error)
}

// NewChatServiceClient constructs a client for the talon.v1.ChatService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewChatServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ChatServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	chatServiceMethods := v1.File_talon_v1_chat_proto.Services().ByName("ChatService").Methods()
	return &chatServiceClient{
		send: connect.NewClient[v1.ChatSendRequest, v1.ChatSendResponse](
			httpClient,
			baseURL+ChatServiceSendProcedure,
			connect.WithSchema(chatServiceMethods.ByName("Send")),
			connect.WithClientOptions(opts...),
		),
		history: connect.NewClient[v1.ChatHistoryRequest, v1.JSONPayload](
			httpClient,
			baseURL+ChatServiceHistoryProcedure,
			connect.WithSchema(chatServiceMethods.ByName("History")),
			connect.WithClientOptions(opts...),
		),
		subscribe: connect.NewClient[v1.ChatSubscribeRequest, v1.ChatEvent](
			httpClient,
			baseURL+ChatServiceSubscribeProcedure,
			connect.WithSchema(chatServiceMethods.ByName("Subscribe")),
			connect.WithClientOptions(opts...),
		),
	}
}

// chatServiceClient implements ChatServiceClient.
type chatServiceClient struct {
	send      *connect.Client[v1.ChatSendRequest, v1.ChatSendResponse]
	history   *connect.Client[v1.ChatHistoryRequest, v1.JSONPayload]
	subscribe *connect.Client[v1.ChatSubscribeRequest, v1.ChatEvent]
}

// Send calls talon.v1.ChatService.Send.
func (c *chatServiceClient) Send(ctx context.Context, req *connect.Request[v1.ChatSendRequest]) (*connect.Response[v1.ChatSendResponse], error) {
	return c.send.CallUnary(ctx, req)
}

// History calls talon.v1.ChatService.History.
func (c *chatServiceClient) History(ctx context.Context, req *connect.Request[v1.ChatHistoryRequest]) (*connect.Response[v1.JSONPayload], error) {
	return c.history.CallUnary(ctx, req)
}

// Subscribe calls talon.v1.ChatService.Subscribe.
func (c *chatServiceClient) Subscribe(ctx context.Context, req *connect.Request[v1.ChatSubscribeRequest]) (*connect.ServerStreamForClient[v1.ChatEvent], error) {
	return c.subscribe.CallServerStream(ctx, req)
}

// ChatServiceHandler is an implementation of the talon.v1.ChatService service.
type ChatServiceHandler interface {
	// Send accepts a user turn and returns the run ID immediately.
	// Events for the run flow on Subscribe — keeping send and
	// subscribe separate matches the existing WS contract so
	// frontends migrate one call at a time.
	Send(context.Context, *connect.Request[v1.ChatSendRequest]) (*connect.Response[v1.ChatSendResponse], error)
	// History returns the recorded turns for a session.
	History(context.Context, *connect.Request[v1.ChatHistoryRequest]) (*connect.Response[v1.JSONPayload], error)
	// Subscribe opens a server-stream of chat events scoped to a
	// session. Filters by run when run_id is set.
	Subscribe(context.Context, *connect.Request[v1.ChatSubscribeRequest], *connect.ServerStream[v1.ChatEvent]) error
}

// NewChatServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewChatServiceHandler(svc ChatServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	chatServiceMethods := v1.File_talon_v1_chat_proto.Services().ByName("ChatService").Methods()
	chatServiceSendHandler := connect.NewUnaryHandler(
		ChatServiceSendProcedure,
		svc.Send,
		connect.WithSchema(chatServiceMethods.ByName("Send")),
		connect.WithHandlerOptions(opts...),
	)
	chatServiceHistoryHandler := connect.NewUnaryHandler(
		ChatServiceHistoryProcedure,
		svc.History,
		connect.WithSchema(chatServiceMethods.ByName("History")),
		connect.WithHandlerOptions(opts...),
	)
	chatServiceSubscribeHandler := connect.NewServerStreamHandler(
		ChatServiceSubscribeProcedure,
		svc.Subscribe,
		connect.WithSchema(chatServiceMethods.ByName("Subscribe")),
		connect.WithHandlerOptions(opts...),
	)
	return "/talon.v1.ChatService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ChatServiceSendProcedure:
			chatServiceSendHandler.ServeHTTP(w, r)
		case ChatServiceHistoryProcedure:
			chatServiceHistoryHandler.ServeHTTP(w, r)
		case ChatServiceSubscribeProcedure:
			chatServiceSubscribeHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedChatServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedChatServiceHandler struct{}

func (UnimplementedChatServiceHandler) Send(context.Context, *connect.Request[v1.ChatSendRequest]) (*connect.Response[v1.ChatSendResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("talon.v1.ChatService.Send is not implemented"))
}

func (UnimplementedChatServiceHandler) History(context.Context, *connect.Request[v1.ChatHistoryRequest]) (*connect.Response[v1.JSONPayload], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("talon.v1.ChatService.History is not implemented"))
}

func (UnimplementedChatServiceHandler) Subscribe(context.Context, *connect.Request[v1.ChatSubscribeRequest], *connect.ServerStream[v1.ChatEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("talon.v1.ChatService.Subscribe is not implemented"))
}
