// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: talon/v1/config.proto

package talonv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/guygrigsby/talon/internal/api/v1/talon/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ConfigServiceName is the fully-qualified name of the ConfigService service.
	ConfigServiceName = "talon.v1.ConfigService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ConfigServiceGetProcedure is the fully-qualified name of the ConfigService's Get RPC.
	ConfigServiceGetProcedure = "/talon.v1.ConfigService/Get"
	// ConfigServiceSchemaProcedure is the fully-qualified name of the ConfigService's Schema RPC.
	ConfigServiceSchemaProcedure = "/talon.v1.ConfigService/Schema"
	// ConfigServiceSetProcedure is the fully-qualified name of the ConfigService's Set RPC.
	ConfigServiceSetProcedure = "/talon.v1.ConfigService/Set"
)

// ConfigServiceClient is a client for the talon.v1.ConfigService service.
type ConfigServiceClient interface {
	// Get returns the value at the requested dotted path, or the
	// whole merged config when path is empty.
	Get(context.Context, *connect.Request[v1.ConfigGetRequest]) (*connect.Response[v1.JSONPayload], error)
	// Schema returns the cached config JSON schema (refreshed via
	// `talon config schema --refresh` on the CLI side).
	Schema(context.Context, *connect.Request[v1.ConfigSchemaRequest]) (*connect.Response[v1.JSONPayload], error)
	// Set writes value_json at path into the talon overlay. Empty
	// value_json deletes the path. Always writes the overlay; never
	// the openclaw layer (which is read-only).
	Set(context.Context, *connect.Request[v1.ConfigSetRequest]) (*connect.Response[v1.JSONPayload], error)
}

// NewConfigServiceClient constructs a client for the talon.v1.ConfigService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewConfigServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ConfigServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	configServiceMethods := v1.File_talon_v1_config_proto.Services().ByName("ConfigService").Methods()
	return &configServiceClient{
		get: connect.NewClient[v1.ConfigGetRequest, v1.JSONPayload](
			httpClient,
			baseURL+ConfigServiceGetProcedure,
			connect.WithSchema(configServiceMethods.ByName("Get")),
			connect.WithClientOptions(opts...),
		),
		schema: connect.NewClient[v1.ConfigSchemaRequest, v1.JSONPayload](
			httpClient,
			baseURL+ConfigServiceSchemaProcedure,
			connect.WithSchema(configServiceMethods.ByName("Schema")),
			connect.WithClientOptions(opts...),
		),
		set: connect.NewClient[v1.ConfigSetRequest, v1.JSONPayload](
			httpClient,
			baseURL+ConfigServiceSetProcedure,
			connect.WithSchema(configServiceMethods.ByName("Set")),
			connect.WithClientOptions(opts...),
		),
	}
}

// configServiceClient implements ConfigServiceClient.
type configServiceClient struct {
	get    *connect.Client[v1.ConfigGetRequest, v1.JSONPayload]
	schema *connect.Client[v1.ConfigSchemaRequest, v1.JSONPayload]
	set    *connect.Client[v1.ConfigSetRequest, v1.JSONPayload]
}

// Get calls talon.v1.ConfigService.Get.
func (c *configServiceClient) Get(ctx context.Context, req *connect.Request[v1.ConfigGetRequest]) (*connect.Response[v1.JSONPayload], error) {
	return c.get.CallUnary(ctx, req)
}

// Schema calls talon.v1.ConfigService.Schema.
func (c *configServiceClient) Schema(ctx context.Context, req *connect.Request[v1.ConfigSchemaRequest]) (*connect.Response[v1.JSONPayload], error) {
	return c.schema.CallUnary(ctx, req)
}

// Set calls talon.v1.ConfigService.Set.
func (c *configServiceClient) Set(ctx context.Context, req *connect.Request[v1.ConfigSetRequest]) (*connect.Response[v1.JSONPayload], error) {
	return c.set.CallUnary(ctx, req)
}

// ConfigServiceHandler is an implementation of the talon.v1.ConfigService service.
type ConfigServiceHandler interface {
	// Get returns the value at the requested dotted path, or the
	// whole merged config when path is empty.
	Get(context.Context, *connect.Request[v1.ConfigGetRequest]) (*connect.Response[v1.JSONPayload], error)
	// Schema returns the cached config JSON schema (refreshed via
	// `talon config schema --refresh` on the CLI side).
	Schema(context.Context, *connect.Request[v1.ConfigSchemaRequest]) (*connect.Response[v1.JSONPayload], error)
	// Set writes value_json at path into the talon overlay. Empty
	// value_json deletes the path. Always writes the overlay; never
	// the openclaw layer (which is read-only).
	Set(context.Context, *connect.Request[v1.ConfigSetRequest]) (*connect.Response[v1.JSONPayload], error)
}

// NewConfigServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewConfigServiceHandler(svc ConfigServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	configServiceMethods := v1.File_talon_v1_config_proto.Services().ByName("ConfigService").Methods()
	configServiceGetHandler := connect.NewUnaryHandler(
		ConfigServiceGetProcedure,
		svc.Get,
		connect.WithSchema(configServiceMethods.ByName("Get")),
		connect.WithHandlerOptions(opts...),
	)
	configServiceSchemaHandler := connect.NewUnaryHandler(
		ConfigServiceSchemaProcedure,
		svc.Schema,
		connect.WithSchema(configServiceMethods.ByName("Schema")),
		connect.WithHandlerOptions(opts...),
	)
	configServiceSetHandler := connect.NewUnaryHandler(
		ConfigServiceSetProcedure,
		svc.Set,
		connect.WithSchema(configServiceMethods.ByName("Set")),
		connect.WithHandlerOptions(opts...),
	)
	return "/talon.v1.ConfigService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ConfigServiceGetProcedure:
			configServiceGetHandler.ServeHTTP(w, r)
		case ConfigServiceSchemaProcedure:
			configServiceSchemaHandler.ServeHTTP(w, r)
		case ConfigServiceSetProcedure:
			configServiceSetHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedConfigServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedConfigServiceHandler struct{}

func (UnimplementedConfigServiceHandler) Get(context.Context, *connect.Request[v1.ConfigGetRequest]) (*connect.Response[v1.JSONPayload], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("talon.v1.ConfigService.Get is not implemented"))
}

func (UnimplementedConfigServiceHandler) Schema(context.Context, *connect.Request[v1.ConfigSchemaRequest]) (*connect.Response[v1.JSONPayload], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("talon.v1.ConfigService.Schema is not implemented"))
}

func (UnimplementedConfigServiceHandler) Set(context.Context, *connect.Request[v1.ConfigSetRequest]) (*connect.Response[v1.JSONPayload], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("talon.v1.ConfigService.Set is not implemented"))
}
