// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: talon/v1/cron.proto

package talonv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/guygrigsby/talon/internal/api/v1/talon/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// CronServiceName is the fully-qualified name of the CronService service.
	CronServiceName = "talon.v1.CronService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// CronServiceListProcedure is the fully-qualified name of the CronService's List RPC.
	CronServiceListProcedure = "/talon.v1.CronService/List"
	// CronServiceAddProcedure is the fully-qualified name of the CronService's Add RPC.
	CronServiceAddProcedure = "/talon.v1.CronService/Add"
	// CronServiceRemoveProcedure is the fully-qualified name of the CronService's Remove RPC.
	CronServiceRemoveProcedure = "/talon.v1.CronService/Remove"
	// CronServiceRunProcedure is the fully-qualified name of the CronService's Run RPC.
	CronServiceRunProcedure = "/talon.v1.CronService/Run"
	// CronServiceStatusProcedure is the fully-qualified name of the CronService's Status RPC.
	CronServiceStatusProcedure = "/talon.v1.CronService/Status"
	// CronServiceShowProcedure is the fully-qualified name of the CronService's Show RPC.
	CronServiceShowProcedure = "/talon.v1.CronService/Show"
	// CronServiceEnableProcedure is the fully-qualified name of the CronService's Enable RPC.
	CronServiceEnableProcedure = "/talon.v1.CronService/Enable"
	// CronServiceDisableProcedure is the fully-qualified name of the CronService's Disable RPC.
	CronServiceDisableProcedure = "/talon.v1.CronService/Disable"
	// CronServiceRunsProcedure is the fully-qualified name of the CronService's Runs RPC.
	CronServiceRunsProcedure = "/talon.v1.CronService/Runs"
)

// CronServiceClient is a client for the talon.v1.CronService service.
type CronServiceClient interface {
	List(context.Context, *connect.Request[v1.CronListRequest]) (*connect.Response[v1.JSONPayload], error)
	Add(context.Context, *connect.Request[v1.JSONPayload]) (*connect.Response[v1.JSONPayload], error)
	Remove(context.Context, *connect.Request[v1.CronJobIDRequest]) (*connect.Response[v1.Empty], error)
	Run(context.Context, *connect.Request[v1.CronJobIDRequest]) (*connect.Response[v1.JSONPayload], error)
	Status(context.Context, *connect.Request[v1.Empty]) (*connect.Response[v1.JSONPayload], error)
	Show(context.Context, *connect.Request[v1.CronJobIDRequest]) (*connect.Response[v1.JSONPayload], error)
	Enable(context.Context, *connect.Request[v1.CronJobIDRequest]) (*connect.Response[v1.Empty], error)
	Disable(context.Context, *connect.Request[v1.CronJobIDRequest]) (*connect.Response[v1.Empty], error)
	Runs(context.Context, *connect.Request[v1.CronRunsRequest]) (*connect.Response[v1.JSONPayload], error)
}

// NewCronServiceClient constructs a client for the talon.v1.CronService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewCronServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) CronServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	cronServiceMethods := v1.File_talon_v1_cron_proto.Services().ByName("CronService").Methods()
	return &cronServiceClient{
		list: connect.NewClient[v1.CronListRequest, v1.JSONPayload](
			httpClient,
			baseURL+CronServiceListProcedure,
			connect.WithSchema(cronServiceMethods.ByName("List")),
			connect.WithClientOptions(opts...),
		),
		add: connect.NewClient[v1.JSONPayload, v1.JSONPayload](
			httpClient,
			baseURL+CronServiceAddProcedure,
			connect.WithSchema(cronServiceMethods.ByName("Add")),
			connect.WithClientOptions(opts...),
		),
		remove: connect.NewClient[v1.CronJobIDRequest, v1.Empty](
			httpClient,
			baseURL+CronServiceRemoveProcedure,
			connect.WithSchema(cronServiceMethods.ByName("Remove")),
			connect.WithClientOptions(opts...),
		),
		run: connect.NewClient[v1.CronJobIDRequest, v1.JSONPayload](
			httpClient,
			baseURL+CronServiceRunProcedure,
			connect.WithSchema(cronServiceMethods.ByName("Run")),
			connect.WithClientOptions(opts...),
		),
		status: connect.NewClient[v1.Empty, v1.JSONPayload](
			httpClient,
			baseURL+CronServiceStatusProcedure,
			connect.WithSchema(cronServiceMethods.ByName("Status")),
			connect.WithClientOptions(opts...),
		),
		show: connect.NewClient[v1.CronJobIDRequest, v1.JSONPayload](
			httpClient,
			baseURL+CronServiceShowProcedure,
			connect.WithSchema(cronServiceMethods.ByName("Show")),
			connect.WithClientOptions(opts...),
		),
		enable: connect.NewClient[v1.CronJobIDRequest, v1.Empty](
			httpClient,
			baseURL+CronServiceEnableProcedure,
			connect.WithSchema(cronServiceMethods.ByName("Enable")),
			connect.WithClientOptions(opts...),
		),
		disable: connect.NewClient[v1.CronJobIDRequest, v1.Empty](
			httpClient,
			baseURL+CronServiceDisableProcedure,
			connect.WithSchema(cronServiceMethods.ByName("Disable")),
			connect.WithClientOptions(opts...),
		),
		runs: connect.NewClient[v1.CronRunsRequest, v1.JSONPayload](
			httpClient,
			baseURL+CronServiceRunsProcedure,
			connect.WithSchema(cronServiceMethods.ByName("Runs")),
			connect.WithClientOptions(opts...),
		),
	}
}

// cronServiceClient implements CronServiceClient.
type cronServiceClient struct {
	list    *connect.Client[v1.CronListRequest, v1.JSONPayload]
	add     *connect.Client[v1.JSONPayload, v1.JSONPayload]
	remove  *connect.Client[v1.CronJobIDRequest, v1.Empty]
	run     *connect.Client[v1.CronJobIDRequest, v1.JSONPayload]
	status  *connect.Client[v1.Empty, v1.JSONPayload]
	show    *connect.Client[v1.CronJobIDRequest, v1.JSONPayload]
	enable  *connect.Client[v1.CronJobIDRequest, v1.Empty]
	disable *connect.Client[v1.CronJobIDRequest, v1.Empty]
	runs    *connect.Client[v1.CronRunsRequest, v1.JSONPayload]
}

// List calls talon.v1.CronService.List.
func (c *cronServiceClient) List(ctx context.Context, req *connect.Request[v1.CronListRequest]) (*connect.Response[v1.JSONPayload], error) {
	return c.list.CallUnary(ctx, req)
}

// Add calls talon.v1.CronService.Add.
func (c *cronServiceClient) Add(ctx context.Context, req *connect.Request[v1.JSONPayload]) (*connect.Response[v1.JSONPayload], error) {
	return c.add.CallUnary(ctx, req)
}

// Remove calls talon.v1.CronService.Remove.
func (c *cronServiceClient) Remove(ctx context.Context, req *connect.Request[v1.CronJobIDRequest]) (*connect.Response[v1.Empty], error) {
	return c.remove.CallUnary(ctx, req)
}

// Run calls talon.v1.CronService.Run.
func (c *cronServiceClient) Run(ctx context.Context, req *connect.Request[v1.CronJobIDRequest]) (*connect.Response[v1.JSONPayload], error) {
	return c.run.CallUnary(ctx, req)
}

// Status calls talon.v1.CronService.Status.
func (c *cronServiceClient) Status(ctx context.Context, req *connect.Request[v1.Empty]) (*connect.Response[v1.JSONPayload], error) {
	return c.status.CallUnary(ctx, req)
}

// Show calls talon.v1.CronService.Show.
func (c *cronServiceClient) Show(ctx context.Context, req *connect.Request[v1.CronJobIDRequest]) (*connect.Response[v1.JSONPayload], error) {
	return c.show.CallUnary(ctx, req)
}

// Enable calls talon.v1.CronService.Enable.
func (c *cronServiceClient) Enable(ctx context.Context, req *connect.Request[v1.CronJobIDRequest]) (*connect.Response[v1.Empty], error) {
	return c.enable.CallUnary(ctx, req)
}

// Disable calls talon.v1.CronService.Disable.
func (c *cronServiceClient) Disable(ctx context.Context, req *connect.Request[v1.CronJobIDRequest]) (*connect.Response[v1.Empty], error) {
	return c.disable.CallUnary(ctx, req)
}

// Runs calls talon.v1.CronService.Runs.
func (c *cronServiceClient) Runs(ctx context.Context, req *connect.Request[v1.CronRunsRequest]) (*connect.Response[v1.JSONPayload], error) {
	return c.runs.CallUnary(ctx, req)
}

// CronServiceHandler is an implementation of the talon.v1.CronService service.
type CronServiceHandler interface {
	List(context.Context, *connect.Request[v1.CronListRequest]) (*connect.Response[v1.JSONPayload], error)
	Add(context.Context, *connect.Request[v1.JSONPayload]) (*connect.Response[v1.JSONPayload], error)
	Remove(context.Context, *connect.Request[v1.CronJobIDRequest]) (*connect.Response[v1.Empty], error)
	Run(context.Context, *connect.Request[v1.CronJobIDRequest]) (*connect.Response[v1.JSONPayload], error)
	Status(context.Context, *connect.Request[v1.Empty]) (*connect.Response[v1.JSONPayload], error)
	Show(context.Context, *connect.Request[v1.CronJobIDRequest]) (*connect.Response[v1.JSONPayload], error)
	Enable(context.Context, *connect.Request[v1.CronJobIDRequest]) (*connect.Response[v1.Empty], error)
	Disable(context.Context, *connect.Request[v1.CronJobIDRequest]) (*connect.Response[v1.Empty], error)
	Runs(context.Context, *connect.Request[v1.CronRunsRequest]) (*connect.Response[v1.JSONPayload], error)
}

// NewCronServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewCronServiceHandler(svc CronServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	cronServiceMethods := v1.File_talon_v1_cron_proto.Services().ByName("CronService").Methods()
	cronServiceListHandler := connect.NewUnaryHandler(
		CronServiceListProcedure,
		svc.List,
		connect.WithSchema(cronServiceMethods.ByName("List")),
		connect.WithHandlerOptions(opts...),
	)
	cronServiceAddHandler := connect.NewUnaryHandler(
		CronServiceAddProcedure,
		svc.Add,
		connect.WithSchema(cronServiceMethods.ByName("Add")),
		connect.WithHandlerOptions(opts...),
	)
	cronServiceRemoveHandler := connect.NewUnaryHandler(
		CronServiceRemoveProcedure,
		svc.Remove,
		connect.WithSchema(cronServiceMethods.ByName("Remove")),
		connect.WithHandlerOptions(opts...),
	)
	cronServiceRunHandler := connect.NewUnaryHandler(
		CronServiceRunProcedure,
		svc.Run,
		connect.WithSchema(cronServiceMethods.ByName("Run")),
		connect.WithHandlerOptions(opts...),
	)
	cronServiceStatusHandler := connect.NewUnaryHandler(
		CronServiceStatusProcedure,
		svc.Status,
		connect.WithSchema(cronServiceMethods.ByName("Status")),
		connect.WithHandlerOptions(opts...),
	)
	cronServiceShowHandler := connect.NewUnaryHandler(
		CronServiceShowProcedure,
		svc.Show,
		connect.WithSchema(cronServiceMethods.ByName("Show")),
		connect.WithHandlerOptions(opts...),
	)
	cronServiceEnableHandler := connect.NewUnaryHandler(
		CronServiceEnableProcedure,
		svc.Enable,
		connect.WithSchema(cronServiceMethods.ByName("Enable")),
		connect.WithHandlerOptions(opts...),
	)
	cronServiceDisableHandler := connect.NewUnaryHandler(
		CronServiceDisableProcedure,
		svc.Disable,
		connect.WithSchema(cronServiceMethods.ByName("Disable")),
		connect.WithHandlerOptions(opts...),
	)
	cronServiceRunsHandler := connect.NewUnaryHandler(
		CronServiceRunsProcedure,
		svc.Runs,
		connect.WithSchema(cronServiceMethods.ByName("Runs")),
		connect.WithHandlerOptions(opts...),
	)
	return "/talon.v1.CronService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case CronServiceListProcedure:
			cronServiceListHandler.ServeHTTP(w, r)
		case CronServiceAddProcedure:
			cronServiceAddHandler.ServeHTTP(w, r)
		case CronServiceRemoveProcedure:
			cronServiceRemoveHandler.ServeHTTP(w, r)
		case CronServiceRunProcedure:
			cronServiceRunHandler.ServeHTTP(w, r)
		case CronServiceStatusProcedure:
			cronServiceStatusHandler.ServeHTTP(w, r)
		case CronServiceShowProcedure:
			cronServiceShowHandler.ServeHTTP(w, r)
		case CronServiceEnableProcedure:
			cronServiceEnableHandler.ServeHTTP(w, r)
		case CronServiceDisableProcedure:
			cronServiceDisableHandler.ServeHTTP(w, r)
		case CronServiceRunsProcedure:
			cronServiceRunsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedCronServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedCronServiceHandler struct{}

func (UnimplementedCronServiceHandler) List(context.Context, *connect.Request[v1.CronListRequest]) (*connect.Response[v1.JSONPayload], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("talon.v1.CronService.List is not implemented"))
}

func (UnimplementedCronServiceHandler) Add(context.Context, *connect.Request[v1.JSONPayload]) (*connect.Response[v1.JSONPayload], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("talon.v1.CronService.Add is not implemented"))
}

func (UnimplementedCronServiceHandler) Remove(context.Context, *connect.Request[v1.CronJobIDRequest]) (*connect.Response[v1.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("talon.v1.CronService.Remove is not implemented"))
}

func (UnimplementedCronServiceHandler) Run(context.Context, *connect.Request[v1.CronJobIDRequest]) (*connect.Response[v1.JSONPayload], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("talon.v1.CronService.Run is not implemented"))
}

func (UnimplementedCronServiceHandler) Status(context.Context, *connect.Request[v1.Empty]) (*connect.Response[v1.JSONPayload], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("talon.v1.CronService.Status is not implemented"))
}

func (UnimplementedCronServiceHandler) Show(context.Context, *connect.Request[v1.CronJobIDRequest]) (*connect.Response[v1.JSONPayload], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("talon.v1.CronService.Show is not implemented"))
}

func (UnimplementedCronServiceHandler) Enable(context.Context, *connect.Request[v1.CronJobIDRequest]) (*connect.Response[v1.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("talon.v1.CronService.Enable is not implemented"))
}

func (UnimplementedCronServiceHandler) Disable(context.Context, *connect.Request[v1.CronJobIDRequest]) (*connect.Response[v1.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("talon.v1.CronService.Disable is not implemented"))
}

func (UnimplementedCronServiceHandler) Runs(context.Context, *connect.Request[v1.CronRunsRequest]) (*connect.Response[v1.JSONPayload], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("talon.v1.CronService.Runs is not implemented"))
}
