// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: talon/v1/infra.proto

package talonv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/guygrigsby/talon/internal/api/v1/talon/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// InfraServiceName is the fully-qualified name of the InfraService service.
	InfraServiceName = "talon.v1.InfraService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// InfraServiceHealthProcedure is the fully-qualified name of the InfraService's Health RPC.
	InfraServiceHealthProcedure = "/talon.v1.InfraService/Health"
	// InfraServiceNodeListProcedure is the fully-qualified name of the InfraService's NodeList RPC.
	InfraServiceNodeListProcedure = "/talon.v1.InfraService/NodeList"
)

// InfraServiceClient is a client for the talon.v1.InfraService service.
type InfraServiceClient interface {
	// Health returns liveness + version info. Maps from WS "health".
	Health(context.Context, *connect.Request[v1.Empty]) (*connect.Response[v1.HealthResponse], error)
	// NodeList enumerates paired/remote nodes (stub today — talon
	// is single-process per talon-4cd; returns empty list).
	NodeList(context.Context, *connect.Request[v1.Empty]) (*connect.Response[v1.NodeListResponse], error)
}

// NewInfraServiceClient constructs a client for the talon.v1.InfraService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewInfraServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) InfraServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	infraServiceMethods := v1.File_talon_v1_infra_proto.Services().ByName("InfraService").Methods()
	return &infraServiceClient{
		health: connect.NewClient[v1.Empty, v1.HealthResponse](
			httpClient,
			baseURL+InfraServiceHealthProcedure,
			connect.WithSchema(infraServiceMethods.ByName("Health")),
			connect.WithClientOptions(opts...),
		),
		nodeList: connect.NewClient[v1.Empty, v1.NodeListResponse](
			httpClient,
			baseURL+InfraServiceNodeListProcedure,
			connect.WithSchema(infraServiceMethods.ByName("NodeList")),
			connect.WithClientOptions(opts...),
		),
	}
}

// infraServiceClient implements InfraServiceClient.
type infraServiceClient struct {
	health   *connect.Client[v1.Empty, v1.HealthResponse]
	nodeList *connect.Client[v1.Empty, v1.NodeListResponse]
}

// Health calls talon.v1.InfraService.Health.
func (c *infraServiceClient) Health(ctx context.Context, req *connect.Request[v1.Empty]) (*connect.Response[v1.HealthResponse], error) {
	return c.health.CallUnary(ctx, req)
}

// NodeList calls talon.v1.InfraService.NodeList.
func (c *infraServiceClient) NodeList(ctx context.Context, req *connect.Request[v1.Empty]) (*connect.Response[v1.NodeListResponse], error) {
	return c.nodeList.CallUnary(ctx, req)
}

// InfraServiceHandler is an implementation of the talon.v1.InfraService service.
type InfraServiceHandler interface {
	// Health returns liveness + version info. Maps from WS "health".
	Health(context.Context, *connect.Request[v1.Empty]) (*connect.Response[v1.HealthResponse], error)
	// NodeList enumerates paired/remote nodes (stub today — talon
	// is single-process per talon-4cd; returns empty list).
	NodeList(context.Context, *connect.Request[v1.Empty]) (*connect.Response[v1.NodeListResponse], error)
}

// NewInfraServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewInfraServiceHandler(svc InfraServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	infraServiceMethods := v1.File_talon_v1_infra_proto.Services().ByName("InfraService").Methods()
	infraServiceHealthHandler := connect.NewUnaryHandler(
		InfraServiceHealthProcedure,
		svc.Health,
		connect.WithSchema(infraServiceMethods.ByName("Health")),
		connect.WithHandlerOptions(opts...),
	)
	infraServiceNodeListHandler := connect.NewUnaryHandler(
		InfraServiceNodeListProcedure,
		svc.NodeList,
		connect.WithSchema(infraServiceMethods.ByName("NodeList")),
		connect.WithHandlerOptions(opts...),
	)
	return "/talon.v1.InfraService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case InfraServiceHealthProcedure:
			infraServiceHealthHandler.ServeHTTP(w, r)
		case InfraServiceNodeListProcedure:
			infraServiceNodeListHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedInfraServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedInfraServiceHandler struct{}

func (UnimplementedInfraServiceHandler) Health(context.Context, *connect.Request[v1.Empty]) (*connect.Response[v1.HealthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("talon.v1.InfraService.Health is not implemented"))
}

func (UnimplementedInfraServiceHandler) NodeList(context.Context, *connect.Request[v1.Empty]) (*connect.Response[v1.NodeListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("talon.v1.InfraService.NodeList is not implemented"))
}
