// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: talon/v1/models.proto

package talonv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/guygrigsby/talon/internal/api/v1/talon/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ModelsServiceName is the fully-qualified name of the ModelsService service.
	ModelsServiceName = "talon.v1.ModelsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ModelsServiceListProcedure is the fully-qualified name of the ModelsService's List RPC.
	ModelsServiceListProcedure = "/talon.v1.ModelsService/List"
	// ModelsServiceAuthStatusProcedure is the fully-qualified name of the ModelsService's AuthStatus
	// RPC.
	ModelsServiceAuthStatusProcedure = "/talon.v1.ModelsService/AuthStatus"
)

// ModelsServiceClient is a client for the talon.v1.ModelsService service.
type ModelsServiceClient interface {
	// List returns the catalog of available models per provider
	// (built-in catalog + user-config overlays + LM Studio
	// discovery).
	List(context.Context, *connect.Request[v1.Empty]) (*connect.Response[v1.JSONPayload], error)
	// AuthStatus returns per-provider credential status (talon-2aq):
	// ok / missing per provider based on auth-profiles.json
	// presence. No expiry tracking yet (talon-aws).
	AuthStatus(context.Context, *connect.Request[v1.ModelsAuthStatusRequest]) (*connect.Response[v1.JSONPayload], error)
}

// NewModelsServiceClient constructs a client for the talon.v1.ModelsService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewModelsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ModelsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	modelsServiceMethods := v1.File_talon_v1_models_proto.Services().ByName("ModelsService").Methods()
	return &modelsServiceClient{
		list: connect.NewClient[v1.Empty, v1.JSONPayload](
			httpClient,
			baseURL+ModelsServiceListProcedure,
			connect.WithSchema(modelsServiceMethods.ByName("List")),
			connect.WithClientOptions(opts...),
		),
		authStatus: connect.NewClient[v1.ModelsAuthStatusRequest, v1.JSONPayload](
			httpClient,
			baseURL+ModelsServiceAuthStatusProcedure,
			connect.WithSchema(modelsServiceMethods.ByName("AuthStatus")),
			connect.WithClientOptions(opts...),
		),
	}
}

// modelsServiceClient implements ModelsServiceClient.
type modelsServiceClient struct {
	list       *connect.Client[v1.Empty, v1.JSONPayload]
	authStatus *connect.Client[v1.ModelsAuthStatusRequest, v1.JSONPayload]
}

// List calls talon.v1.ModelsService.List.
func (c *modelsServiceClient) List(ctx context.Context, req *connect.Request[v1.Empty]) (*connect.Response[v1.JSONPayload], error) {
	return c.list.CallUnary(ctx, req)
}

// AuthStatus calls talon.v1.ModelsService.AuthStatus.
func (c *modelsServiceClient) AuthStatus(ctx context.Context, req *connect.Request[v1.ModelsAuthStatusRequest]) (*connect.Response[v1.JSONPayload], error) {
	return c.authStatus.CallUnary(ctx, req)
}

// ModelsServiceHandler is an implementation of the talon.v1.ModelsService service.
type ModelsServiceHandler interface {
	// List returns the catalog of available models per provider
	// (built-in catalog + user-config overlays + LM Studio
	// discovery).
	List(context.Context, *connect.Request[v1.Empty]) (*connect.Response[v1.JSONPayload], error)
	// AuthStatus returns per-provider credential status (talon-2aq):
	// ok / missing per provider based on auth-profiles.json
	// presence. No expiry tracking yet (talon-aws).
	AuthStatus(context.Context, *connect.Request[v1.ModelsAuthStatusRequest]) (*connect.Response[v1.JSONPayload], error)
}

// NewModelsServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewModelsServiceHandler(svc ModelsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	modelsServiceMethods := v1.File_talon_v1_models_proto.Services().ByName("ModelsService").Methods()
	modelsServiceListHandler := connect.NewUnaryHandler(
		ModelsServiceListProcedure,
		svc.List,
		connect.WithSchema(modelsServiceMethods.ByName("List")),
		connect.WithHandlerOptions(opts...),
	)
	modelsServiceAuthStatusHandler := connect.NewUnaryHandler(
		ModelsServiceAuthStatusProcedure,
		svc.AuthStatus,
		connect.WithSchema(modelsServiceMethods.ByName("AuthStatus")),
		connect.WithHandlerOptions(opts...),
	)
	return "/talon.v1.ModelsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ModelsServiceListProcedure:
			modelsServiceListHandler.ServeHTTP(w, r)
		case ModelsServiceAuthStatusProcedure:
			modelsServiceAuthStatusHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedModelsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedModelsServiceHandler struct{}

func (UnimplementedModelsServiceHandler) List(context.Context, *connect.Request[v1.Empty]) (*connect.Response[v1.JSONPayload], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("talon.v1.ModelsService.List is not implemented"))
}

func (UnimplementedModelsServiceHandler) AuthStatus(context.Context, *connect.Request[v1.ModelsAuthStatusRequest]) (*connect.Response[v1.JSONPayload], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("talon.v1.ModelsService.AuthStatus is not implemented"))
}
