// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: talon/v1/plugins.proto

package talonv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/guygrigsby/talon/internal/api/v1/talon/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PluginsServiceName is the fully-qualified name of the PluginsService service.
	PluginsServiceName = "talon.v1.PluginsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PluginsServiceDepsStatusProcedure is the fully-qualified name of the PluginsService's DepsStatus
	// RPC.
	PluginsServiceDepsStatusProcedure = "/talon.v1.PluginsService/DepsStatus"
	// PluginsServiceDepsInstallProcedure is the fully-qualified name of the PluginsService's
	// DepsInstall RPC.
	PluginsServiceDepsInstallProcedure = "/talon.v1.PluginsService/DepsInstall"
	// PluginsServiceDepsUninstallProcedure is the fully-qualified name of the PluginsService's
	// DepsUninstall RPC.
	PluginsServiceDepsUninstallProcedure = "/talon.v1.PluginsService/DepsUninstall"
	// PluginsServiceDepsDetailProcedure is the fully-qualified name of the PluginsService's DepsDetail
	// RPC.
	PluginsServiceDepsDetailProcedure = "/talon.v1.PluginsService/DepsDetail"
	// PluginsServiceCommandsListProcedure is the fully-qualified name of the PluginsService's
	// CommandsList RPC.
	PluginsServiceCommandsListProcedure = "/talon.v1.PluginsService/CommandsList"
)

// PluginsServiceClient is a client for the talon.v1.PluginsService service.
type PluginsServiceClient interface {
	DepsStatus(context.Context, *connect.Request[v1.Empty]) (*connect.Response[v1.JSONPayload], error)
	DepsInstall(context.Context, *connect.Request[v1.DepsInstallRequest]) (*connect.Response[v1.JSONPayload], error)
	DepsUninstall(context.Context, *connect.Request[v1.DepsUninstallRequest]) (*connect.Response[v1.JSONPayload], error)
	DepsDetail(context.Context, *connect.Request[v1.DepsDetailRequest]) (*connect.Response[v1.JSONPayload], error)
	// CommandsList enumerates registered slash commands across
	// skills + plugins (talon-18k stub today).
	CommandsList(context.Context, *connect.Request[v1.CommandsListRequest]) (*connect.Response[v1.JSONPayload], error)
}

// NewPluginsServiceClient constructs a client for the talon.v1.PluginsService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPluginsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PluginsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	pluginsServiceMethods := v1.File_talon_v1_plugins_proto.Services().ByName("PluginsService").Methods()
	return &pluginsServiceClient{
		depsStatus: connect.NewClient[v1.Empty, v1.JSONPayload](
			httpClient,
			baseURL+PluginsServiceDepsStatusProcedure,
			connect.WithSchema(pluginsServiceMethods.ByName("DepsStatus")),
			connect.WithClientOptions(opts...),
		),
		depsInstall: connect.NewClient[v1.DepsInstallRequest, v1.JSONPayload](
			httpClient,
			baseURL+PluginsServiceDepsInstallProcedure,
			connect.WithSchema(pluginsServiceMethods.ByName("DepsInstall")),
			connect.WithClientOptions(opts...),
		),
		depsUninstall: connect.NewClient[v1.DepsUninstallRequest, v1.JSONPayload](
			httpClient,
			baseURL+PluginsServiceDepsUninstallProcedure,
			connect.WithSchema(pluginsServiceMethods.ByName("DepsUninstall")),
			connect.WithClientOptions(opts...),
		),
		depsDetail: connect.NewClient[v1.DepsDetailRequest, v1.JSONPayload](
			httpClient,
			baseURL+PluginsServiceDepsDetailProcedure,
			connect.WithSchema(pluginsServiceMethods.ByName("DepsDetail")),
			connect.WithClientOptions(opts...),
		),
		commandsList: connect.NewClient[v1.CommandsListRequest, v1.JSONPayload](
			httpClient,
			baseURL+PluginsServiceCommandsListProcedure,
			connect.WithSchema(pluginsServiceMethods.ByName("CommandsList")),
			connect.WithClientOptions(opts...),
		),
	}
}

// pluginsServiceClient implements PluginsServiceClient.
type pluginsServiceClient struct {
	depsStatus    *connect.Client[v1.Empty, v1.JSONPayload]
	depsInstall   *connect.Client[v1.DepsInstallRequest, v1.JSONPayload]
	depsUninstall *connect.Client[v1.DepsUninstallRequest, v1.JSONPayload]
	depsDetail    *connect.Client[v1.DepsDetailRequest, v1.JSONPayload]
	commandsList  *connect.Client[v1.CommandsListRequest, v1.JSONPayload]
}

// DepsStatus calls talon.v1.PluginsService.DepsStatus.
func (c *pluginsServiceClient) DepsStatus(ctx context.Context, req *connect.Request[v1.Empty]) (*connect.Response[v1.JSONPayload], error) {
	return c.depsStatus.CallUnary(ctx, req)
}

// DepsInstall calls talon.v1.PluginsService.DepsInstall.
func (c *pluginsServiceClient) DepsInstall(ctx context.Context, req *connect.Request[v1.DepsInstallRequest]) (*connect.Response[v1.JSONPayload], error) {
	return c.depsInstall.CallUnary(ctx, req)
}

// DepsUninstall calls talon.v1.PluginsService.DepsUninstall.
func (c *pluginsServiceClient) DepsUninstall(ctx context.Context, req *connect.Request[v1.DepsUninstallRequest]) (*connect.Response[v1.JSONPayload], error) {
	return c.depsUninstall.CallUnary(ctx, req)
}

// DepsDetail calls talon.v1.PluginsService.DepsDetail.
func (c *pluginsServiceClient) DepsDetail(ctx context.Context, req *connect.Request[v1.DepsDetailRequest]) (*connect.Response[v1.JSONPayload], error) {
	return c.depsDetail.CallUnary(ctx, req)
}

// CommandsList calls talon.v1.PluginsService.CommandsList.
func (c *pluginsServiceClient) CommandsList(ctx context.Context, req *connect.Request[v1.CommandsListRequest]) (*connect.Response[v1.JSONPayload], error) {
	return c.commandsList.CallUnary(ctx, req)
}

// PluginsServiceHandler is an implementation of the talon.v1.PluginsService service.
type PluginsServiceHandler interface {
	DepsStatus(context.Context, *connect.Request[v1.Empty]) (*connect.Response[v1.JSONPayload], error)
	DepsInstall(context.Context, *connect.Request[v1.DepsInstallRequest]) (*connect.Response[v1.JSONPayload], error)
	DepsUninstall(context.Context, *connect.Request[v1.DepsUninstallRequest]) (*connect.Response[v1.JSONPayload], error)
	DepsDetail(context.Context, *connect.Request[v1.DepsDetailRequest]) (*connect.Response[v1.JSONPayload], error)
	// CommandsList enumerates registered slash commands across
	// skills + plugins (talon-18k stub today).
	CommandsList(context.Context, *connect.Request[v1.CommandsListRequest]) (*connect.Response[v1.JSONPayload], error)
}

// NewPluginsServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPluginsServiceHandler(svc PluginsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	pluginsServiceMethods := v1.File_talon_v1_plugins_proto.Services().ByName("PluginsService").Methods()
	pluginsServiceDepsStatusHandler := connect.NewUnaryHandler(
		PluginsServiceDepsStatusProcedure,
		svc.DepsStatus,
		connect.WithSchema(pluginsServiceMethods.ByName("DepsStatus")),
		connect.WithHandlerOptions(opts...),
	)
	pluginsServiceDepsInstallHandler := connect.NewUnaryHandler(
		PluginsServiceDepsInstallProcedure,
		svc.DepsInstall,
		connect.WithSchema(pluginsServiceMethods.ByName("DepsInstall")),
		connect.WithHandlerOptions(opts...),
	)
	pluginsServiceDepsUninstallHandler := connect.NewUnaryHandler(
		PluginsServiceDepsUninstallProcedure,
		svc.DepsUninstall,
		connect.WithSchema(pluginsServiceMethods.ByName("DepsUninstall")),
		connect.WithHandlerOptions(opts...),
	)
	pluginsServiceDepsDetailHandler := connect.NewUnaryHandler(
		PluginsServiceDepsDetailProcedure,
		svc.DepsDetail,
		connect.WithSchema(pluginsServiceMethods.ByName("DepsDetail")),
		connect.WithHandlerOptions(opts...),
	)
	pluginsServiceCommandsListHandler := connect.NewUnaryHandler(
		PluginsServiceCommandsListProcedure,
		svc.CommandsList,
		connect.WithSchema(pluginsServiceMethods.ByName("CommandsList")),
		connect.WithHandlerOptions(opts...),
	)
	return "/talon.v1.PluginsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PluginsServiceDepsStatusProcedure:
			pluginsServiceDepsStatusHandler.ServeHTTP(w, r)
		case PluginsServiceDepsInstallProcedure:
			pluginsServiceDepsInstallHandler.ServeHTTP(w, r)
		case PluginsServiceDepsUninstallProcedure:
			pluginsServiceDepsUninstallHandler.ServeHTTP(w, r)
		case PluginsServiceDepsDetailProcedure:
			pluginsServiceDepsDetailHandler.ServeHTTP(w, r)
		case PluginsServiceCommandsListProcedure:
			pluginsServiceCommandsListHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPluginsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPluginsServiceHandler struct{}

func (UnimplementedPluginsServiceHandler) DepsStatus(context.Context, *connect.Request[v1.Empty]) (*connect.Response[v1.JSONPayload], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("talon.v1.PluginsService.DepsStatus is not implemented"))
}

func (UnimplementedPluginsServiceHandler) DepsInstall(context.Context, *connect.Request[v1.DepsInstallRequest]) (*connect.Response[v1.JSONPayload], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("talon.v1.PluginsService.DepsInstall is not implemented"))
}

func (UnimplementedPluginsServiceHandler) DepsUninstall(context.Context, *connect.Request[v1.DepsUninstallRequest]) (*connect.Response[v1.JSONPayload], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("talon.v1.PluginsService.DepsUninstall is not implemented"))
}

func (UnimplementedPluginsServiceHandler) DepsDetail(context.Context, *connect.Request[v1.DepsDetailRequest]) (*connect.Response[v1.JSONPayload], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("talon.v1.PluginsService.DepsDetail is not implemented"))
}

func (UnimplementedPluginsServiceHandler) CommandsList(context.Context, *connect.Request[v1.CommandsListRequest]) (*connect.Response[v1.JSONPayload], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("talon.v1.PluginsService.CommandsList is not implemented"))
}
