// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: talon/v1/rpc.proto

package talonv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/guygrigsby/talon/internal/api/v1/talon/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// RpcServiceName is the fully-qualified name of the RpcService service.
	RpcServiceName = "talon.v1.RpcService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// RpcServiceDispatchProcedure is the fully-qualified name of the RpcService's Dispatch RPC.
	RpcServiceDispatchProcedure = "/talon.v1.RpcService/Dispatch"
)

// RpcServiceClient is a client for the talon.v1.RpcService service.
type RpcServiceClient interface {
	// Dispatch invokes one method on the gateway's registry by name.
	// The params are passed through as opaque JSON; the response is
	// returned the same way.
	Dispatch(context.Context, *connect.Request[v1.DispatchRequest]) (*connect.Response[v1.DispatchResponse], error)
}

// NewRpcServiceClient constructs a client for the talon.v1.RpcService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRpcServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RpcServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	rpcServiceMethods := v1.File_talon_v1_rpc_proto.Services().ByName("RpcService").Methods()
	return &rpcServiceClient{
		dispatch: connect.NewClient[v1.DispatchRequest, v1.DispatchResponse](
			httpClient,
			baseURL+RpcServiceDispatchProcedure,
			connect.WithSchema(rpcServiceMethods.ByName("Dispatch")),
			connect.WithClientOptions(opts...),
		),
	}
}

// rpcServiceClient implements RpcServiceClient.
type rpcServiceClient struct {
	dispatch *connect.Client[v1.DispatchRequest, v1.DispatchResponse]
}

// Dispatch calls talon.v1.RpcService.Dispatch.
func (c *rpcServiceClient) Dispatch(ctx context.Context, req *connect.Request[v1.DispatchRequest]) (*connect.Response[v1.DispatchResponse], error) {
	return c.dispatch.CallUnary(ctx, req)
}

// RpcServiceHandler is an implementation of the talon.v1.RpcService service.
type RpcServiceHandler interface {
	// Dispatch invokes one method on the gateway's registry by name.
	// The params are passed through as opaque JSON; the response is
	// returned the same way.
	Dispatch(context.Context, *connect.Request[v1.DispatchRequest]) (*connect.Response[v1.DispatchResponse], error)
}

// NewRpcServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRpcServiceHandler(svc RpcServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	rpcServiceMethods := v1.File_talon_v1_rpc_proto.Services().ByName("RpcService").Methods()
	rpcServiceDispatchHandler := connect.NewUnaryHandler(
		RpcServiceDispatchProcedure,
		svc.Dispatch,
		connect.WithSchema(rpcServiceMethods.ByName("Dispatch")),
		connect.WithHandlerOptions(opts...),
	)
	return "/talon.v1.RpcService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RpcServiceDispatchProcedure:
			rpcServiceDispatchHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRpcServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedRpcServiceHandler struct{}

func (UnimplementedRpcServiceHandler) Dispatch(context.Context, *connect.Request[v1.DispatchRequest]) (*connect.Response[v1.DispatchResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("talon.v1.RpcService.Dispatch is not implemented"))
}
