// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: talon/v1/sessions.proto

package talonv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/guygrigsby/talon/internal/api/v1/talon/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SessionsServiceName is the fully-qualified name of the SessionsService service.
	SessionsServiceName = "talon.v1.SessionsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SessionsServiceListProcedure is the fully-qualified name of the SessionsService's List RPC.
	SessionsServiceListProcedure = "/talon.v1.SessionsService/List"
	// SessionsServicePatchProcedure is the fully-qualified name of the SessionsService's Patch RPC.
	SessionsServicePatchProcedure = "/talon.v1.SessionsService/Patch"
)

// SessionsServiceClient is a client for the talon.v1.SessionsService service.
type SessionsServiceClient interface {
	// List returns the active sessions known to the gateway.
	List(context.Context, *connect.Request[v1.Empty]) (*connect.Response[v1.JSONPayload], error)
	// Patch applies a partial update to a session's state (e.g.
	// model override, system prompt suffix).
	Patch(context.Context, *connect.Request[v1.SessionsPatchRequest]) (*connect.Response[v1.Empty], error)
}

// NewSessionsServiceClient constructs a client for the talon.v1.SessionsService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSessionsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SessionsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	sessionsServiceMethods := v1.File_talon_v1_sessions_proto.Services().ByName("SessionsService").Methods()
	return &sessionsServiceClient{
		list: connect.NewClient[v1.Empty, v1.JSONPayload](
			httpClient,
			baseURL+SessionsServiceListProcedure,
			connect.WithSchema(sessionsServiceMethods.ByName("List")),
			connect.WithClientOptions(opts...),
		),
		patch: connect.NewClient[v1.SessionsPatchRequest, v1.Empty](
			httpClient,
			baseURL+SessionsServicePatchProcedure,
			connect.WithSchema(sessionsServiceMethods.ByName("Patch")),
			connect.WithClientOptions(opts...),
		),
	}
}

// sessionsServiceClient implements SessionsServiceClient.
type sessionsServiceClient struct {
	list  *connect.Client[v1.Empty, v1.JSONPayload]
	patch *connect.Client[v1.SessionsPatchRequest, v1.Empty]
}

// List calls talon.v1.SessionsService.List.
func (c *sessionsServiceClient) List(ctx context.Context, req *connect.Request[v1.Empty]) (*connect.Response[v1.JSONPayload], error) {
	return c.list.CallUnary(ctx, req)
}

// Patch calls talon.v1.SessionsService.Patch.
func (c *sessionsServiceClient) Patch(ctx context.Context, req *connect.Request[v1.SessionsPatchRequest]) (*connect.Response[v1.Empty], error) {
	return c.patch.CallUnary(ctx, req)
}

// SessionsServiceHandler is an implementation of the talon.v1.SessionsService service.
type SessionsServiceHandler interface {
	// List returns the active sessions known to the gateway.
	List(context.Context, *connect.Request[v1.Empty]) (*connect.Response[v1.JSONPayload], error)
	// Patch applies a partial update to a session's state (e.g.
	// model override, system prompt suffix).
	Patch(context.Context, *connect.Request[v1.SessionsPatchRequest]) (*connect.Response[v1.Empty], error)
}

// NewSessionsServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSessionsServiceHandler(svc SessionsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	sessionsServiceMethods := v1.File_talon_v1_sessions_proto.Services().ByName("SessionsService").Methods()
	sessionsServiceListHandler := connect.NewUnaryHandler(
		SessionsServiceListProcedure,
		svc.List,
		connect.WithSchema(sessionsServiceMethods.ByName("List")),
		connect.WithHandlerOptions(opts...),
	)
	sessionsServicePatchHandler := connect.NewUnaryHandler(
		SessionsServicePatchProcedure,
		svc.Patch,
		connect.WithSchema(sessionsServiceMethods.ByName("Patch")),
		connect.WithHandlerOptions(opts...),
	)
	return "/talon.v1.SessionsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SessionsServiceListProcedure:
			sessionsServiceListHandler.ServeHTTP(w, r)
		case SessionsServicePatchProcedure:
			sessionsServicePatchHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSessionsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSessionsServiceHandler struct{}

func (UnimplementedSessionsServiceHandler) List(context.Context, *connect.Request[v1.Empty]) (*connect.Response[v1.JSONPayload], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("talon.v1.SessionsService.List is not implemented"))
}

func (UnimplementedSessionsServiceHandler) Patch(context.Context, *connect.Request[v1.SessionsPatchRequest]) (*connect.Response[v1.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("talon.v1.SessionsService.Patch is not implemented"))
}
