import { t as DEFAULT_CONTEXT_TOKENS } from "../../defaults-Bnf56S7k.js";
import { i as isProxyReasoningUnsupported, n as createOpenRouterSystemCacheWrapper, r as createOpenRouterWrapper } from "../../proxy-stream-wrappers-tB4kzlkp.js";
import { a as buildProviderReplayFamilyHooks } from "../../provider-model-shared-DYKze5ii.js";
import { t as createProviderApiKeyAuthMethod } from "../../provider-api-key-auth-VFVRJax6.js";
import "../../provider-auth-api-key-BPJ9p3Lh.js";
import { c as buildProviderStreamFamilyHooks, l as getOpenRouterModelCapabilities, u as loadOpenRouterModelCapabilities } from "../../provider-stream-U9gr3YL8.js";
import "../../provider-stream-family-B__-4zUv.js";
import { n as buildOpenrouterProvider } from "../../provider-catalog-jkYAQIKQ.js";
import { t as openrouterMediaUnderstandingProvider } from "../../media-understanding-provider-S79JSJCo.js";
import { n as applyOpenrouterConfig, t as OPENROUTER_DEFAULT_MODEL_REF } from "../../onboard-CJBVczvW.js";
import { t as buildOpenRouterSpeechProvider } from "../../speech-provider-Ct2PUShP.js";
export { DEFAULT_CONTEXT_TOKENS, OPENROUTER_DEFAULT_MODEL_REF, applyOpenrouterConfig, buildOpenRouterSpeechProvider, buildOpenrouterProvider, buildProviderReplayFamilyHooks, buildProviderStreamFamilyHooks, createOpenRouterSystemCacheWrapper, createOpenRouterWrapper, createProviderApiKeyAuthMethod, getOpenRouterModelCapabilities, isProxyReasoningUnsupported, loadOpenRouterModelCapabilities, openrouterMediaUnderstandingProvider };
