// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: talon/v1/agents.proto

package talonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentFilesListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentFilesListRequest) Reset() {
	*x = AgentFilesListRequest{}
	mi := &file_talon_v1_agents_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentFilesListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentFilesListRequest) ProtoMessage() {}

func (x *AgentFilesListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_talon_v1_agents_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentFilesListRequest.ProtoReflect.Descriptor instead.
func (*AgentFilesListRequest) Descriptor() ([]byte, []int) {
	return file_talon_v1_agents_proto_rawDescGZIP(), []int{0}
}

func (x *AgentFilesListRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type AgentFilesGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	File          string                 `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentFilesGetRequest) Reset() {
	*x = AgentFilesGetRequest{}
	mi := &file_talon_v1_agents_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentFilesGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentFilesGetRequest) ProtoMessage() {}

func (x *AgentFilesGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_talon_v1_agents_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentFilesGetRequest.ProtoReflect.Descriptor instead.
func (*AgentFilesGetRequest) Descriptor() ([]byte, []int) {
	return file_talon_v1_agents_proto_rawDescGZIP(), []int{1}
}

func (x *AgentFilesGetRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentFilesGetRequest) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

type AgentFilesSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	File          string                 `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentFilesSetRequest) Reset() {
	*x = AgentFilesSetRequest{}
	mi := &file_talon_v1_agents_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentFilesSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentFilesSetRequest) ProtoMessage() {}

func (x *AgentFilesSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_talon_v1_agents_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentFilesSetRequest.ProtoReflect.Descriptor instead.
func (*AgentFilesSetRequest) Descriptor() ([]byte, []int) {
	return file_talon_v1_agents_proto_rawDescGZIP(), []int{2}
}

func (x *AgentFilesSetRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentFilesSetRequest) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *AgentFilesSetRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type AgentIdentityGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionKey    string                 `protobuf:"bytes,1,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentIdentityGetRequest) Reset() {
	*x = AgentIdentityGetRequest{}
	mi := &file_talon_v1_agents_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentIdentityGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentIdentityGetRequest) ProtoMessage() {}

func (x *AgentIdentityGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_talon_v1_agents_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentIdentityGetRequest.ProtoReflect.Descriptor instead.
func (*AgentIdentityGetRequest) Descriptor() ([]byte, []int) {
	return file_talon_v1_agents_proto_rawDescGZIP(), []int{3}
}

func (x *AgentIdentityGetRequest) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

type SkillsStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillsStatusRequest) Reset() {
	*x = SkillsStatusRequest{}
	mi := &file_talon_v1_agents_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillsStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillsStatusRequest) ProtoMessage() {}

func (x *SkillsStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_talon_v1_agents_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillsStatusRequest.ProtoReflect.Descriptor instead.
func (*SkillsStatusRequest) Descriptor() ([]byte, []int) {
	return file_talon_v1_agents_proto_rawDescGZIP(), []int{4}
}

func (x *SkillsStatusRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type MemoryAppendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryAppendRequest) Reset() {
	*x = MemoryAppendRequest{}
	mi := &file_talon_v1_agents_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryAppendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryAppendRequest) ProtoMessage() {}

func (x *MemoryAppendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_talon_v1_agents_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryAppendRequest.ProtoReflect.Descriptor instead.
func (*MemoryAppendRequest) Descriptor() ([]byte, []int) {
	return file_talon_v1_agents_proto_rawDescGZIP(), []int{5}
}

func (x *MemoryAppendRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *MemoryAppendRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *MemoryAppendRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_talon_v1_agents_proto protoreflect.FileDescriptor

const file_talon_v1_agents_proto_rawDesc = "" +
	"\n" +
	"\x15talon/v1/agents.proto\x12\btalon.v1\x1a\x15talon/v1/common.proto\"2\n" +
	"\x15AgentFilesListRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"E\n" +
	"\x14AgentFilesGetRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x12\n" +
	"\x04file\x18\x02 \x01(\tR\x04file\"_\n" +
	"\x14AgentFilesSetRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x12\n" +
	"\x04file\x18\x02 \x01(\tR\x04file\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\":\n" +
	"\x17AgentIdentityGetRequest\x12\x1f\n" +
	"\vsession_key\x18\x01 \x01(\tR\n" +
	"sessionKey\"0\n" +
	"\x13SkillsStatusRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"X\n" +
	"\x13MemoryAppendRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text2\xd3\x03\n" +
	"\rAgentsService\x12.\n" +
	"\x04List\x12\x0f.talon.v1.Empty\x1a\x15.talon.v1.JSONPayload\x12C\n" +
	"\tFilesList\x12\x1f.talon.v1.AgentFilesListRequest\x1a\x15.talon.v1.JSONPayload\x12A\n" +
	"\bFilesGet\x12\x1e.talon.v1.AgentFilesGetRequest\x1a\x15.talon.v1.JSONPayload\x12;\n" +
	"\bFilesSet\x12\x1e.talon.v1.AgentFilesSetRequest\x1a\x0f.talon.v1.Empty\x12G\n" +
	"\vIdentityGet\x12!.talon.v1.AgentIdentityGetRequest\x1a\x15.talon.v1.JSONPayload\x12D\n" +
	"\fSkillsStatus\x12\x1d.talon.v1.SkillsStatusRequest\x1a\x15.talon.v1.JSONPayload\x12>\n" +
	"\fMemoryAppend\x12\x1d.talon.v1.MemoryAppendRequest\x1a\x0f.talon.v1.EmptyB>Z<github.com/guygrigsby/talon/internal/api/v1/talon/v1;talonv1b\x06proto3"

var (
	file_talon_v1_agents_proto_rawDescOnce sync.Once
	file_talon_v1_agents_proto_rawDescData []byte
)

func file_talon_v1_agents_proto_rawDescGZIP() []byte {
	file_talon_v1_agents_proto_rawDescOnce.Do(func() {
		file_talon_v1_agents_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_talon_v1_agents_proto_rawDesc), len(file_talon_v1_agents_proto_rawDesc)))
	})
	return file_talon_v1_agents_proto_rawDescData
}

var file_talon_v1_agents_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_talon_v1_agents_proto_goTypes = []any{
	(*AgentFilesListRequest)(nil),   // 0: talon.v1.AgentFilesListRequest
	(*AgentFilesGetRequest)(nil),    // 1: talon.v1.AgentFilesGetRequest
	(*AgentFilesSetRequest)(nil),    // 2: talon.v1.AgentFilesSetRequest
	(*AgentIdentityGetRequest)(nil), // 3: talon.v1.AgentIdentityGetRequest
	(*SkillsStatusRequest)(nil),     // 4: talon.v1.SkillsStatusRequest
	(*MemoryAppendRequest)(nil),     // 5: talon.v1.MemoryAppendRequest
	(*Empty)(nil),                   // 6: talon.v1.Empty
	(*JSONPayload)(nil),             // 7: talon.v1.JSONPayload
}
var file_talon_v1_agents_proto_depIdxs = []int32{
	6, // 0: talon.v1.AgentsService.List:input_type -> talon.v1.Empty
	0, // 1: talon.v1.AgentsService.FilesList:input_type -> talon.v1.AgentFilesListRequest
	1, // 2: talon.v1.AgentsService.FilesGet:input_type -> talon.v1.AgentFilesGetRequest
	2, // 3: talon.v1.AgentsService.FilesSet:input_type -> talon.v1.AgentFilesSetRequest
	3, // 4: talon.v1.AgentsService.IdentityGet:input_type -> talon.v1.AgentIdentityGetRequest
	4, // 5: talon.v1.AgentsService.SkillsStatus:input_type -> talon.v1.SkillsStatusRequest
	5, // 6: talon.v1.AgentsService.MemoryAppend:input_type -> talon.v1.MemoryAppendRequest
	7, // 7: talon.v1.AgentsService.List:output_type -> talon.v1.JSONPayload
	7, // 8: talon.v1.AgentsService.FilesList:output_type -> talon.v1.JSONPayload
	7, // 9: talon.v1.AgentsService.FilesGet:output_type -> talon.v1.JSONPayload
	6, // 10: talon.v1.AgentsService.FilesSet:output_type -> talon.v1.Empty
	7, // 11: talon.v1.AgentsService.IdentityGet:output_type -> talon.v1.JSONPayload
	7, // 12: talon.v1.AgentsService.SkillsStatus:output_type -> talon.v1.JSONPayload
	6, // 13: talon.v1.AgentsService.MemoryAppend:output_type -> talon.v1.Empty
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_talon_v1_agents_proto_init() }
func file_talon_v1_agents_proto_init() {
	if File_talon_v1_agents_proto != nil {
		return
	}
	file_talon_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_talon_v1_agents_proto_rawDesc), len(file_talon_v1_agents_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_talon_v1_agents_proto_goTypes,
		DependencyIndexes: file_talon_v1_agents_proto_depIdxs,
		MessageInfos:      file_talon_v1_agents_proto_msgTypes,
	}.Build()
	File_talon_v1_agents_proto = out.File
	file_talon_v1_agents_proto_goTypes = nil
	file_talon_v1_agents_proto_depIdxs = nil
}
