// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: talon/v1/channels.proto

package talonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TelegramVerifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotToken      string                 `protobuf:"bytes,1,opt,name=bot_token,json=botToken,proto3" json:"bot_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelegramVerifyRequest) Reset() {
	*x = TelegramVerifyRequest{}
	mi := &file_talon_v1_channels_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelegramVerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelegramVerifyRequest) ProtoMessage() {}

func (x *TelegramVerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_talon_v1_channels_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelegramVerifyRequest.ProtoReflect.Descriptor instead.
func (*TelegramVerifyRequest) Descriptor() ([]byte, []int) {
	return file_talon_v1_channels_proto_rawDescGZIP(), []int{0}
}

func (x *TelegramVerifyRequest) GetBotToken() string {
	if x != nil {
		return x.BotToken
	}
	return ""
}

type TelegramCaptureSenderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotToken      string                 `protobuf:"bytes,1,opt,name=bot_token,json=botToken,proto3" json:"bot_token,omitempty"`
	TimeoutMs     int64                  `protobuf:"varint,2,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelegramCaptureSenderRequest) Reset() {
	*x = TelegramCaptureSenderRequest{}
	mi := &file_talon_v1_channels_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelegramCaptureSenderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelegramCaptureSenderRequest) ProtoMessage() {}

func (x *TelegramCaptureSenderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_talon_v1_channels_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelegramCaptureSenderRequest.ProtoReflect.Descriptor instead.
func (*TelegramCaptureSenderRequest) Descriptor() ([]byte, []int) {
	return file_talon_v1_channels_proto_rawDescGZIP(), []int{1}
}

func (x *TelegramCaptureSenderRequest) GetBotToken() string {
	if x != nil {
		return x.BotToken
	}
	return ""
}

func (x *TelegramCaptureSenderRequest) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type TelegramPersistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	BotToken      string                 `protobuf:"bytes,2,opt,name=bot_token,json=botToken,proto3" json:"bot_token,omitempty"`
	ChatId        int64                  `protobuf:"varint,3,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Confirm       bool                   `protobuf:"varint,4,opt,name=confirm,proto3" json:"confirm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelegramPersistRequest) Reset() {
	*x = TelegramPersistRequest{}
	mi := &file_talon_v1_channels_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelegramPersistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelegramPersistRequest) ProtoMessage() {}

func (x *TelegramPersistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_talon_v1_channels_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelegramPersistRequest.ProtoReflect.Descriptor instead.
func (*TelegramPersistRequest) Descriptor() ([]byte, []int) {
	return file_talon_v1_channels_proto_rawDescGZIP(), []int{2}
}

func (x *TelegramPersistRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *TelegramPersistRequest) GetBotToken() string {
	if x != nil {
		return x.BotToken
	}
	return ""
}

func (x *TelegramPersistRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *TelegramPersistRequest) GetConfirm() bool {
	if x != nil {
		return x.Confirm
	}
	return false
}

var File_talon_v1_channels_proto protoreflect.FileDescriptor

const file_talon_v1_channels_proto_rawDesc = "" +
	"\n" +
	"\x17talon/v1/channels.proto\x12\btalon.v1\x1a\x15talon/v1/common.proto\"4\n" +
	"\x15TelegramVerifyRequest\x12\x1b\n" +
	"\tbot_token\x18\x01 \x01(\tR\bbotToken\"Z\n" +
	"\x1cTelegramCaptureSenderRequest\x12\x1b\n" +
	"\tbot_token\x18\x01 \x01(\tR\bbotToken\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x02 \x01(\x03R\ttimeoutMs\"\x83\x01\n" +
	"\x16TelegramPersistRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1b\n" +
	"\tbot_token\x18\x02 \x01(\tR\bbotToken\x12\x17\n" +
	"\achat_id\x18\x03 \x01(\x03R\x06chatId\x12\x18\n" +
	"\aconfirm\x18\x04 \x01(\bR\aconfirm2\xf9\x01\n" +
	"\x0fChannelsService\x12H\n" +
	"\x0eTelegramVerify\x12\x1f.talon.v1.TelegramVerifyRequest\x1a\x15.talon.v1.JSONPayload\x12V\n" +
	"\x15TelegramCaptureSender\x12&.talon.v1.TelegramCaptureSenderRequest\x1a\x15.talon.v1.JSONPayload\x12D\n" +
	"\x0fTelegramPersist\x12 .talon.v1.TelegramPersistRequest\x1a\x0f.talon.v1.EmptyB>Z<github.com/guygrigsby/talon/internal/api/v1/talon/v1;talonv1b\x06proto3"

var (
	file_talon_v1_channels_proto_rawDescOnce sync.Once
	file_talon_v1_channels_proto_rawDescData []byte
)

func file_talon_v1_channels_proto_rawDescGZIP() []byte {
	file_talon_v1_channels_proto_rawDescOnce.Do(func() {
		file_talon_v1_channels_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_talon_v1_channels_proto_rawDesc), len(file_talon_v1_channels_proto_rawDesc)))
	})
	return file_talon_v1_channels_proto_rawDescData
}

var file_talon_v1_channels_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_talon_v1_channels_proto_goTypes = []any{
	(*TelegramVerifyRequest)(nil),        // 0: talon.v1.TelegramVerifyRequest
	(*TelegramCaptureSenderRequest)(nil), // 1: talon.v1.TelegramCaptureSenderRequest
	(*TelegramPersistRequest)(nil),       // 2: talon.v1.TelegramPersistRequest
	(*JSONPayload)(nil),                  // 3: talon.v1.JSONPayload
	(*Empty)(nil),                        // 4: talon.v1.Empty
}
var file_talon_v1_channels_proto_depIdxs = []int32{
	0, // 0: talon.v1.ChannelsService.TelegramVerify:input_type -> talon.v1.TelegramVerifyRequest
	1, // 1: talon.v1.ChannelsService.TelegramCaptureSender:input_type -> talon.v1.TelegramCaptureSenderRequest
	2, // 2: talon.v1.ChannelsService.TelegramPersist:input_type -> talon.v1.TelegramPersistRequest
	3, // 3: talon.v1.ChannelsService.TelegramVerify:output_type -> talon.v1.JSONPayload
	3, // 4: talon.v1.ChannelsService.TelegramCaptureSender:output_type -> talon.v1.JSONPayload
	4, // 5: talon.v1.ChannelsService.TelegramPersist:output_type -> talon.v1.Empty
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_talon_v1_channels_proto_init() }
func file_talon_v1_channels_proto_init() {
	if File_talon_v1_channels_proto != nil {
		return
	}
	file_talon_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_talon_v1_channels_proto_rawDesc), len(file_talon_v1_channels_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_talon_v1_channels_proto_goTypes,
		DependencyIndexes: file_talon_v1_channels_proto_depIdxs,
		MessageInfos:      file_talon_v1_channels_proto_msgTypes,
	}.Build()
	File_talon_v1_channels_proto = out.File
	file_talon_v1_channels_proto_goTypes = nil
	file_talon_v1_channels_proto_depIdxs = nil
}
