// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: talon/v1/chat.proto

package talonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatSendRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionKey     string                 `protobuf:"bytes,1,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// Model, when set, overrides the agent's default for this turn.
	Model string `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	// System, when set, suffixes the agent's system prompt for this
	// turn only.
	System        string `protobuf:"bytes,5,opt,name=system,proto3" json:"system,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatSendRequest) Reset() {
	*x = ChatSendRequest{}
	mi := &file_talon_v1_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatSendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatSendRequest) ProtoMessage() {}

func (x *ChatSendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_talon_v1_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatSendRequest.ProtoReflect.Descriptor instead.
func (*ChatSendRequest) Descriptor() ([]byte, []int) {
	return file_talon_v1_chat_proto_rawDescGZIP(), []int{0}
}

func (x *ChatSendRequest) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

func (x *ChatSendRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatSendRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *ChatSendRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatSendRequest) GetSystem() string {
	if x != nil {
		return x.System
	}
	return ""
}

type ChatSendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatSendResponse) Reset() {
	*x = ChatSendResponse{}
	mi := &file_talon_v1_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatSendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatSendResponse) ProtoMessage() {}

func (x *ChatSendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_talon_v1_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatSendResponse.ProtoReflect.Descriptor instead.
func (*ChatSendResponse) Descriptor() ([]byte, []int) {
	return file_talon_v1_chat_proto_rawDescGZIP(), []int{1}
}

func (x *ChatSendResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type ChatHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionKey    string                 `protobuf:"bytes,1,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatHistoryRequest) Reset() {
	*x = ChatHistoryRequest{}
	mi := &file_talon_v1_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatHistoryRequest) ProtoMessage() {}

func (x *ChatHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_talon_v1_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatHistoryRequest.ProtoReflect.Descriptor instead.
func (*ChatHistoryRequest) Descriptor() ([]byte, []int) {
	return file_talon_v1_chat_proto_rawDescGZIP(), []int{2}
}

func (x *ChatHistoryRequest) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

type ChatSubscribeRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	SessionKey string                 `protobuf:"bytes,1,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	// RunID, when set, narrows the stream to one run.
	RunId         string `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatSubscribeRequest) Reset() {
	*x = ChatSubscribeRequest{}
	mi := &file_talon_v1_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatSubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatSubscribeRequest) ProtoMessage() {}

func (x *ChatSubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_talon_v1_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatSubscribeRequest.ProtoReflect.Descriptor instead.
func (*ChatSubscribeRequest) Descriptor() ([]byte, []int) {
	return file_talon_v1_chat_proto_rawDescGZIP(), []int{3}
}

func (x *ChatSubscribeRequest) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

func (x *ChatSubscribeRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

// ChatEvent is the envelope every server-pushed chat-stream
// payload arrives in. Mirrors the WS frame's Event + Payload
// shape so the migration is one-line on the consumer side.
type ChatEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         string                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	PayloadJson   string                 `protobuf:"bytes,2,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"` // JSON-string-pass-through, see common.proto JSONPayload
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatEvent) Reset() {
	*x = ChatEvent{}
	mi := &file_talon_v1_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatEvent) ProtoMessage() {}

func (x *ChatEvent) ProtoReflect() protoreflect.Message {
	mi := &file_talon_v1_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatEvent.ProtoReflect.Descriptor instead.
func (*ChatEvent) Descriptor() ([]byte, []int) {
	return file_talon_v1_chat_proto_rawDescGZIP(), []int{4}
}

func (x *ChatEvent) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *ChatEvent) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

var File_talon_v1_chat_proto protoreflect.FileDescriptor

const file_talon_v1_chat_proto_rawDesc = "" +
	"\n" +
	"\x13talon/v1/chat.proto\x12\btalon.v1\x1a\x15talon/v1/common.proto\"\xa3\x01\n" +
	"\x0fChatSendRequest\x12\x1f\n" +
	"\vsession_key\x18\x01 \x01(\tR\n" +
	"sessionKey\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x16\n" +
	"\x06system\x18\x05 \x01(\tR\x06system\")\n" +
	"\x10ChatSendResponse\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"5\n" +
	"\x12ChatHistoryRequest\x12\x1f\n" +
	"\vsession_key\x18\x01 \x01(\tR\n" +
	"sessionKey\"N\n" +
	"\x14ChatSubscribeRequest\x12\x1f\n" +
	"\vsession_key\x18\x01 \x01(\tR\n" +
	"sessionKey\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\"D\n" +
	"\tChatEvent\x12\x14\n" +
	"\x05event\x18\x01 \x01(\tR\x05event\x12!\n" +
	"\fpayload_json\x18\x02 \x01(\tR\vpayloadJson2\xd0\x01\n" +
	"\vChatService\x12=\n" +
	"\x04Send\x12\x19.talon.v1.ChatSendRequest\x1a\x1a.talon.v1.ChatSendResponse\x12>\n" +
	"\aHistory\x12\x1c.talon.v1.ChatHistoryRequest\x1a\x15.talon.v1.JSONPayload\x12B\n" +
	"\tSubscribe\x12\x1e.talon.v1.ChatSubscribeRequest\x1a\x13.talon.v1.ChatEvent0\x01B>Z<github.com/guygrigsby/talon/internal/api/v1/talon/v1;talonv1b\x06proto3"

var (
	file_talon_v1_chat_proto_rawDescOnce sync.Once
	file_talon_v1_chat_proto_rawDescData []byte
)

func file_talon_v1_chat_proto_rawDescGZIP() []byte {
	file_talon_v1_chat_proto_rawDescOnce.Do(func() {
		file_talon_v1_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_talon_v1_chat_proto_rawDesc), len(file_talon_v1_chat_proto_rawDesc)))
	})
	return file_talon_v1_chat_proto_rawDescData
}

var file_talon_v1_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_talon_v1_chat_proto_goTypes = []any{
	(*ChatSendRequest)(nil),      // 0: talon.v1.ChatSendRequest
	(*ChatSendResponse)(nil),     // 1: talon.v1.ChatSendResponse
	(*ChatHistoryRequest)(nil),   // 2: talon.v1.ChatHistoryRequest
	(*ChatSubscribeRequest)(nil), // 3: talon.v1.ChatSubscribeRequest
	(*ChatEvent)(nil),            // 4: talon.v1.ChatEvent
	(*JSONPayload)(nil),          // 5: talon.v1.JSONPayload
}
var file_talon_v1_chat_proto_depIdxs = []int32{
	0, // 0: talon.v1.ChatService.Send:input_type -> talon.v1.ChatSendRequest
	2, // 1: talon.v1.ChatService.History:input_type -> talon.v1.ChatHistoryRequest
	3, // 2: talon.v1.ChatService.Subscribe:input_type -> talon.v1.ChatSubscribeRequest
	1, // 3: talon.v1.ChatService.Send:output_type -> talon.v1.ChatSendResponse
	5, // 4: talon.v1.ChatService.History:output_type -> talon.v1.JSONPayload
	4, // 5: talon.v1.ChatService.Subscribe:output_type -> talon.v1.ChatEvent
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_talon_v1_chat_proto_init() }
func file_talon_v1_chat_proto_init() {
	if File_talon_v1_chat_proto != nil {
		return
	}
	file_talon_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_talon_v1_chat_proto_rawDesc), len(file_talon_v1_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_talon_v1_chat_proto_goTypes,
		DependencyIndexes: file_talon_v1_chat_proto_depIdxs,
		MessageInfos:      file_talon_v1_chat_proto_msgTypes,
	}.Build()
	File_talon_v1_chat_proto = out.File
	file_talon_v1_chat_proto_goTypes = nil
	file_talon_v1_chat_proto_depIdxs = nil
}
