// Shared message types used across multiple talon services.
// Names mirror the JSON shapes the existing WS handlers produce
// so the Connect adapter is a thin JSON re-marshal, not a
// translation layer with its own schema.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: talon/v1/common.proto

package talonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Empty is the zero-payload request/response, used by methods
// that take no input or return no output. google.protobuf.Empty
// would do but pulling in well-known-types just for one message
// isn't worth the extra dep — keeping it local.
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_talon_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_talon_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_talon_v1_common_proto_rawDescGZIP(), []int{0}
}

// JSONPayload carries an arbitrary JSON-encoded value. Used by
// config.{get,schema}, agents.list, models.list, cron.*, and
// anywhere else the response shape is dynamic enough that
// declaring it in proto would be churn.
//
// Type is `string` not `bytes`: Connect's JSON encoder base64-
// encodes proto bytes fields, which would force every consumer
// to decode-then-parse. Strings pass through as JSON strings
// (escaped) so consumers can JSON.parse(json) directly.
type JSONPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          string                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JSONPayload) Reset() {
	*x = JSONPayload{}
	mi := &file_talon_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JSONPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JSONPayload) ProtoMessage() {}

func (x *JSONPayload) ProtoReflect() protoreflect.Message {
	mi := &file_talon_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JSONPayload.ProtoReflect.Descriptor instead.
func (*JSONPayload) Descriptor() ([]byte, []int) {
	return file_talon_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *JSONPayload) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

var File_talon_v1_common_proto protoreflect.FileDescriptor

const file_talon_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x15talon/v1/common.proto\x12\btalon.v1\"\a\n" +
	"\x05Empty\"!\n" +
	"\vJSONPayload\x12\x12\n" +
	"\x04json\x18\x01 \x01(\tR\x04jsonB>Z<github.com/guygrigsby/talon/internal/api/v1/talon/v1;talonv1b\x06proto3"

var (
	file_talon_v1_common_proto_rawDescOnce sync.Once
	file_talon_v1_common_proto_rawDescData []byte
)

func file_talon_v1_common_proto_rawDescGZIP() []byte {
	file_talon_v1_common_proto_rawDescOnce.Do(func() {
		file_talon_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_talon_v1_common_proto_rawDesc), len(file_talon_v1_common_proto_rawDesc)))
	})
	return file_talon_v1_common_proto_rawDescData
}

var file_talon_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_talon_v1_common_proto_goTypes = []any{
	(*Empty)(nil),       // 0: talon.v1.Empty
	(*JSONPayload)(nil), // 1: talon.v1.JSONPayload
}
var file_talon_v1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_talon_v1_common_proto_init() }
func file_talon_v1_common_proto_init() {
	if File_talon_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_talon_v1_common_proto_rawDesc), len(file_talon_v1_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_talon_v1_common_proto_goTypes,
		DependencyIndexes: file_talon_v1_common_proto_depIdxs,
		MessageInfos:      file_talon_v1_common_proto_msgTypes,
	}.Build()
	File_talon_v1_common_proto = out.File
	file_talon_v1_common_proto_goTypes = nil
	file_talon_v1_common_proto_depIdxs = nil
}
