// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: talon/v1/cron.proto

package talonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CronListRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IncludeDisabled bool                   `protobuf:"varint,1,opt,name=include_disabled,json=includeDisabled,proto3" json:"include_disabled,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CronListRequest) Reset() {
	*x = CronListRequest{}
	mi := &file_talon_v1_cron_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CronListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CronListRequest) ProtoMessage() {}

func (x *CronListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_talon_v1_cron_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CronListRequest.ProtoReflect.Descriptor instead.
func (*CronListRequest) Descriptor() ([]byte, []int) {
	return file_talon_v1_cron_proto_rawDescGZIP(), []int{0}
}

func (x *CronListRequest) GetIncludeDisabled() bool {
	if x != nil {
		return x.IncludeDisabled
	}
	return false
}

type CronJobIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CronJobIDRequest) Reset() {
	*x = CronJobIDRequest{}
	mi := &file_talon_v1_cron_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CronJobIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CronJobIDRequest) ProtoMessage() {}

func (x *CronJobIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_talon_v1_cron_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CronJobIDRequest.ProtoReflect.Descriptor instead.
func (*CronJobIDRequest) Descriptor() ([]byte, []int) {
	return file_talon_v1_cron_proto_rawDescGZIP(), []int{1}
}

func (x *CronJobIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CronRunsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CronRunsRequest) Reset() {
	*x = CronRunsRequest{}
	mi := &file_talon_v1_cron_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CronRunsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CronRunsRequest) ProtoMessage() {}

func (x *CronRunsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_talon_v1_cron_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CronRunsRequest.ProtoReflect.Descriptor instead.
func (*CronRunsRequest) Descriptor() ([]byte, []int) {
	return file_talon_v1_cron_proto_rawDescGZIP(), []int{2}
}

func (x *CronRunsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CronRunsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_talon_v1_cron_proto protoreflect.FileDescriptor

const file_talon_v1_cron_proto_rawDesc = "" +
	"\n" +
	"\x13talon/v1/cron.proto\x12\btalon.v1\x1a\x15talon/v1/common.proto\"<\n" +
	"\x0fCronListRequest\x12)\n" +
	"\x10include_disabled\x18\x01 \x01(\bR\x0fincludeDisabled\"\"\n" +
	"\x10CronJobIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"7\n" +
	"\x0fCronRunsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit2\x83\x04\n" +
	"\vCronService\x128\n" +
	"\x04List\x12\x19.talon.v1.CronListRequest\x1a\x15.talon.v1.JSONPayload\x123\n" +
	"\x03Add\x12\x15.talon.v1.JSONPayload\x1a\x15.talon.v1.JSONPayload\x125\n" +
	"\x06Remove\x12\x1a.talon.v1.CronJobIDRequest\x1a\x0f.talon.v1.Empty\x128\n" +
	"\x03Run\x12\x1a.talon.v1.CronJobIDRequest\x1a\x15.talon.v1.JSONPayload\x120\n" +
	"\x06Status\x12\x0f.talon.v1.Empty\x1a\x15.talon.v1.JSONPayload\x129\n" +
	"\x04Show\x12\x1a.talon.v1.CronJobIDRequest\x1a\x15.talon.v1.JSONPayload\x125\n" +
	"\x06Enable\x12\x1a.talon.v1.CronJobIDRequest\x1a\x0f.talon.v1.Empty\x126\n" +
	"\aDisable\x12\x1a.talon.v1.CronJobIDRequest\x1a\x0f.talon.v1.Empty\x128\n" +
	"\x04Runs\x12\x19.talon.v1.CronRunsRequest\x1a\x15.talon.v1.JSONPayloadB>Z<github.com/guygrigsby/talon/internal/api/v1/talon/v1;talonv1b\x06proto3"

var (
	file_talon_v1_cron_proto_rawDescOnce sync.Once
	file_talon_v1_cron_proto_rawDescData []byte
)

func file_talon_v1_cron_proto_rawDescGZIP() []byte {
	file_talon_v1_cron_proto_rawDescOnce.Do(func() {
		file_talon_v1_cron_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_talon_v1_cron_proto_rawDesc), len(file_talon_v1_cron_proto_rawDesc)))
	})
	return file_talon_v1_cron_proto_rawDescData
}

var file_talon_v1_cron_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_talon_v1_cron_proto_goTypes = []any{
	(*CronListRequest)(nil),  // 0: talon.v1.CronListRequest
	(*CronJobIDRequest)(nil), // 1: talon.v1.CronJobIDRequest
	(*CronRunsRequest)(nil),  // 2: talon.v1.CronRunsRequest
	(*JSONPayload)(nil),      // 3: talon.v1.JSONPayload
	(*Empty)(nil),            // 4: talon.v1.Empty
}
var file_talon_v1_cron_proto_depIdxs = []int32{
	0, // 0: talon.v1.CronService.List:input_type -> talon.v1.CronListRequest
	3, // 1: talon.v1.CronService.Add:input_type -> talon.v1.JSONPayload
	1, // 2: talon.v1.CronService.Remove:input_type -> talon.v1.CronJobIDRequest
	1, // 3: talon.v1.CronService.Run:input_type -> talon.v1.CronJobIDRequest
	4, // 4: talon.v1.CronService.Status:input_type -> talon.v1.Empty
	1, // 5: talon.v1.CronService.Show:input_type -> talon.v1.CronJobIDRequest
	1, // 6: talon.v1.CronService.Enable:input_type -> talon.v1.CronJobIDRequest
	1, // 7: talon.v1.CronService.Disable:input_type -> talon.v1.CronJobIDRequest
	2, // 8: talon.v1.CronService.Runs:input_type -> talon.v1.CronRunsRequest
	3, // 9: talon.v1.CronService.List:output_type -> talon.v1.JSONPayload
	3, // 10: talon.v1.CronService.Add:output_type -> talon.v1.JSONPayload
	4, // 11: talon.v1.CronService.Remove:output_type -> talon.v1.Empty
	3, // 12: talon.v1.CronService.Run:output_type -> talon.v1.JSONPayload
	3, // 13: talon.v1.CronService.Status:output_type -> talon.v1.JSONPayload
	3, // 14: talon.v1.CronService.Show:output_type -> talon.v1.JSONPayload
	4, // 15: talon.v1.CronService.Enable:output_type -> talon.v1.Empty
	4, // 16: talon.v1.CronService.Disable:output_type -> talon.v1.Empty
	3, // 17: talon.v1.CronService.Runs:output_type -> talon.v1.JSONPayload
	9, // [9:18] is the sub-list for method output_type
	0, // [0:9] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_talon_v1_cron_proto_init() }
func file_talon_v1_cron_proto_init() {
	if File_talon_v1_cron_proto != nil {
		return
	}
	file_talon_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_talon_v1_cron_proto_rawDesc), len(file_talon_v1_cron_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_talon_v1_cron_proto_goTypes,
		DependencyIndexes: file_talon_v1_cron_proto_depIdxs,
		MessageInfos:      file_talon_v1_cron_proto_msgTypes,
	}.Build()
	File_talon_v1_cron_proto = out.File
	file_talon_v1_cron_proto_goTypes = nil
	file_talon_v1_cron_proto_depIdxs = nil
}
