// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: talon/v1/infra.proto

package talonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Server        string                 `protobuf:"bytes,2,opt,name=server,proto3" json:"server,omitempty"`
	UptimeMs      int64                  `protobuf:"varint,3,opt,name=uptime_ms,json=uptimeMs,proto3" json:"uptime_ms,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_talon_v1_infra_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_talon_v1_infra_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_talon_v1_infra_proto_rawDescGZIP(), []int{0}
}

func (x *HealthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HealthResponse) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *HealthResponse) GetUptimeMs() int64 {
	if x != nil {
		return x.UptimeMs
	}
	return 0
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type NodeListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*Node                `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeListResponse) Reset() {
	*x = NodeListResponse{}
	mi := &file_talon_v1_infra_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeListResponse) ProtoMessage() {}

func (x *NodeListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_talon_v1_infra_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeListResponse.ProtoReflect.Descriptor instead.
func (*NodeListResponse) Descriptor() ([]byte, []int) {
	return file_talon_v1_infra_proto_rawDescGZIP(), []int{1}
}

func (x *NodeListResponse) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Connected     bool                   `protobuf:"varint,3,opt,name=connected,proto3" json:"connected,omitempty"`
	Commands      []string               `protobuf:"bytes,4,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_talon_v1_infra_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_talon_v1_infra_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_talon_v1_infra_proto_rawDescGZIP(), []int{2}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Node) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *Node) GetCommands() []string {
	if x != nil {
		return x.Commands
	}
	return nil
}

var File_talon_v1_infra_proto protoreflect.FileDescriptor

const file_talon_v1_infra_proto_rawDesc = "" +
	"\n" +
	"\x14talon/v1/infra.proto\x12\btalon.v1\x1a\x15talon/v1/common.proto\"o\n" +
	"\x0eHealthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06server\x18\x02 \x01(\tR\x06server\x12\x1b\n" +
	"\tuptime_ms\x18\x03 \x01(\x03R\buptimeMs\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\"8\n" +
	"\x10NodeListResponse\x12$\n" +
	"\x05nodes\x18\x01 \x03(\v2\x0e.talon.v1.NodeR\x05nodes\"d\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tconnected\x18\x03 \x01(\bR\tconnected\x12\x1a\n" +
	"\bcommands\x18\x04 \x03(\tR\bcommands2|\n" +
	"\fInfraService\x123\n" +
	"\x06Health\x12\x0f.talon.v1.Empty\x1a\x18.talon.v1.HealthResponse\x127\n" +
	"\bNodeList\x12\x0f.talon.v1.Empty\x1a\x1a.talon.v1.NodeListResponseB>Z<github.com/guygrigsby/talon/internal/api/v1/talon/v1;talonv1b\x06proto3"

var (
	file_talon_v1_infra_proto_rawDescOnce sync.Once
	file_talon_v1_infra_proto_rawDescData []byte
)

func file_talon_v1_infra_proto_rawDescGZIP() []byte {
	file_talon_v1_infra_proto_rawDescOnce.Do(func() {
		file_talon_v1_infra_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_talon_v1_infra_proto_rawDesc), len(file_talon_v1_infra_proto_rawDesc)))
	})
	return file_talon_v1_infra_proto_rawDescData
}

var file_talon_v1_infra_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_talon_v1_infra_proto_goTypes = []any{
	(*HealthResponse)(nil),   // 0: talon.v1.HealthResponse
	(*NodeListResponse)(nil), // 1: talon.v1.NodeListResponse
	(*Node)(nil),             // 2: talon.v1.Node
	(*Empty)(nil),            // 3: talon.v1.Empty
}
var file_talon_v1_infra_proto_depIdxs = []int32{
	2, // 0: talon.v1.NodeListResponse.nodes:type_name -> talon.v1.Node
	3, // 1: talon.v1.InfraService.Health:input_type -> talon.v1.Empty
	3, // 2: talon.v1.InfraService.NodeList:input_type -> talon.v1.Empty
	0, // 3: talon.v1.InfraService.Health:output_type -> talon.v1.HealthResponse
	1, // 4: talon.v1.InfraService.NodeList:output_type -> talon.v1.NodeListResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_talon_v1_infra_proto_init() }
func file_talon_v1_infra_proto_init() {
	if File_talon_v1_infra_proto != nil {
		return
	}
	file_talon_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_talon_v1_infra_proto_rawDesc), len(file_talon_v1_infra_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_talon_v1_infra_proto_goTypes,
		DependencyIndexes: file_talon_v1_infra_proto_depIdxs,
		MessageInfos:      file_talon_v1_infra_proto_msgTypes,
	}.Build()
	File_talon_v1_infra_proto = out.File
	file_talon_v1_infra_proto_goTypes = nil
	file_talon_v1_infra_proto_depIdxs = nil
}
