// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: talon/v1/models.proto

package talonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ModelsAuthStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	Refresh       bool                   `protobuf:"varint,3,opt,name=refresh,proto3" json:"refresh,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelsAuthStatusRequest) Reset() {
	*x = ModelsAuthStatusRequest{}
	mi := &file_talon_v1_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelsAuthStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelsAuthStatusRequest) ProtoMessage() {}

func (x *ModelsAuthStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_talon_v1_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelsAuthStatusRequest.ProtoReflect.Descriptor instead.
func (*ModelsAuthStatusRequest) Descriptor() ([]byte, []int) {
	return file_talon_v1_models_proto_rawDescGZIP(), []int{0}
}

func (x *ModelsAuthStatusRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ModelsAuthStatusRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ModelsAuthStatusRequest) GetRefresh() bool {
	if x != nil {
		return x.Refresh
	}
	return false
}

var File_talon_v1_models_proto protoreflect.FileDescriptor

const file_talon_v1_models_proto_rawDesc = "" +
	"\n" +
	"\x15talon/v1/models.proto\x12\btalon.v1\x1a\x15talon/v1/common.proto\"j\n" +
	"\x17ModelsAuthStatusRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x18\n" +
	"\arefresh\x18\x03 \x01(\bR\arefresh2\x87\x01\n" +
	"\rModelsService\x12.\n" +
	"\x04List\x12\x0f.talon.v1.Empty\x1a\x15.talon.v1.JSONPayload\x12F\n" +
	"\n" +
	"AuthStatus\x12!.talon.v1.ModelsAuthStatusRequest\x1a\x15.talon.v1.JSONPayloadB>Z<github.com/guygrigsby/talon/internal/api/v1/talon/v1;talonv1b\x06proto3"

var (
	file_talon_v1_models_proto_rawDescOnce sync.Once
	file_talon_v1_models_proto_rawDescData []byte
)

func file_talon_v1_models_proto_rawDescGZIP() []byte {
	file_talon_v1_models_proto_rawDescOnce.Do(func() {
		file_talon_v1_models_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_talon_v1_models_proto_rawDesc), len(file_talon_v1_models_proto_rawDesc)))
	})
	return file_talon_v1_models_proto_rawDescData
}

var file_talon_v1_models_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_talon_v1_models_proto_goTypes = []any{
	(*ModelsAuthStatusRequest)(nil), // 0: talon.v1.ModelsAuthStatusRequest
	(*Empty)(nil),                   // 1: talon.v1.Empty
	(*JSONPayload)(nil),             // 2: talon.v1.JSONPayload
}
var file_talon_v1_models_proto_depIdxs = []int32{
	1, // 0: talon.v1.ModelsService.List:input_type -> talon.v1.Empty
	0, // 1: talon.v1.ModelsService.AuthStatus:input_type -> talon.v1.ModelsAuthStatusRequest
	2, // 2: talon.v1.ModelsService.List:output_type -> talon.v1.JSONPayload
	2, // 3: talon.v1.ModelsService.AuthStatus:output_type -> talon.v1.JSONPayload
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_talon_v1_models_proto_init() }
func file_talon_v1_models_proto_init() {
	if File_talon_v1_models_proto != nil {
		return
	}
	file_talon_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_talon_v1_models_proto_rawDesc), len(file_talon_v1_models_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_talon_v1_models_proto_goTypes,
		DependencyIndexes: file_talon_v1_models_proto_depIdxs,
		MessageInfos:      file_talon_v1_models_proto_msgTypes,
	}.Build()
	File_talon_v1_models_proto = out.File
	file_talon_v1_models_proto_goTypes = nil
	file_talon_v1_models_proto_depIdxs = nil
}
