// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: talon/v1/plugins.proto

package talonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DepsInstallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         string                 `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepsInstallRequest) Reset() {
	*x = DepsInstallRequest{}
	mi := &file_talon_v1_plugins_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepsInstallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepsInstallRequest) ProtoMessage() {}

func (x *DepsInstallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_talon_v1_plugins_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepsInstallRequest.ProtoReflect.Descriptor instead.
func (*DepsInstallRequest) Descriptor() ([]byte, []int) {
	return file_talon_v1_plugins_proto_rawDescGZIP(), []int{0}
}

func (x *DepsInstallRequest) GetEntry() string {
	if x != nil {
		return x.Entry
	}
	return ""
}

type DepsUninstallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         string                 `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepsUninstallRequest) Reset() {
	*x = DepsUninstallRequest{}
	mi := &file_talon_v1_plugins_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepsUninstallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepsUninstallRequest) ProtoMessage() {}

func (x *DepsUninstallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_talon_v1_plugins_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepsUninstallRequest.ProtoReflect.Descriptor instead.
func (*DepsUninstallRequest) Descriptor() ([]byte, []int) {
	return file_talon_v1_plugins_proto_rawDescGZIP(), []int{1}
}

func (x *DepsUninstallRequest) GetEntry() string {
	if x != nil {
		return x.Entry
	}
	return ""
}

type DepsDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         string                 `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepsDetailRequest) Reset() {
	*x = DepsDetailRequest{}
	mi := &file_talon_v1_plugins_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepsDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepsDetailRequest) ProtoMessage() {}

func (x *DepsDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_talon_v1_plugins_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepsDetailRequest.ProtoReflect.Descriptor instead.
func (*DepsDetailRequest) Descriptor() ([]byte, []int) {
	return file_talon_v1_plugins_proto_rawDescGZIP(), []int{2}
}

func (x *DepsDetailRequest) GetEntry() string {
	if x != nil {
		return x.Entry
	}
	return ""
}

type CommandsListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	Scope         string                 `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	IncludeArgs   bool                   `protobuf:"varint,4,opt,name=include_args,json=includeArgs,proto3" json:"include_args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandsListRequest) Reset() {
	*x = CommandsListRequest{}
	mi := &file_talon_v1_plugins_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandsListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandsListRequest) ProtoMessage() {}

func (x *CommandsListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_talon_v1_plugins_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandsListRequest.ProtoReflect.Descriptor instead.
func (*CommandsListRequest) Descriptor() ([]byte, []int) {
	return file_talon_v1_plugins_proto_rawDescGZIP(), []int{3}
}

func (x *CommandsListRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CommandsListRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *CommandsListRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *CommandsListRequest) GetIncludeArgs() bool {
	if x != nil {
		return x.IncludeArgs
	}
	return false
}

var File_talon_v1_plugins_proto protoreflect.FileDescriptor

const file_talon_v1_plugins_proto_rawDesc = "" +
	"\n" +
	"\x16talon/v1/plugins.proto\x12\btalon.v1\x1a\x15talon/v1/common.proto\"*\n" +
	"\x12DepsInstallRequest\x12\x14\n" +
	"\x05entry\x18\x01 \x01(\tR\x05entry\",\n" +
	"\x14DepsUninstallRequest\x12\x14\n" +
	"\x05entry\x18\x01 \x01(\tR\x05entry\")\n" +
	"\x11DepsDetailRequest\x12\x14\n" +
	"\x05entry\x18\x01 \x01(\tR\x05entry\"\x85\x01\n" +
	"\x13CommandsListRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x14\n" +
	"\x05scope\x18\x03 \x01(\tR\x05scope\x12!\n" +
	"\finclude_args\x18\x04 \x01(\bR\vincludeArgs2\xda\x02\n" +
	"\x0ePluginsService\x124\n" +
	"\n" +
	"DepsStatus\x12\x0f.talon.v1.Empty\x1a\x15.talon.v1.JSONPayload\x12B\n" +
	"\vDepsInstall\x12\x1c.talon.v1.DepsInstallRequest\x1a\x15.talon.v1.JSONPayload\x12F\n" +
	"\rDepsUninstall\x12\x1e.talon.v1.DepsUninstallRequest\x1a\x15.talon.v1.JSONPayload\x12@\n" +
	"\n" +
	"DepsDetail\x12\x1b.talon.v1.DepsDetailRequest\x1a\x15.talon.v1.JSONPayload\x12D\n" +
	"\fCommandsList\x12\x1d.talon.v1.CommandsListRequest\x1a\x15.talon.v1.JSONPayloadB>Z<github.com/guygrigsby/talon/internal/api/v1/talon/v1;talonv1b\x06proto3"

var (
	file_talon_v1_plugins_proto_rawDescOnce sync.Once
	file_talon_v1_plugins_proto_rawDescData []byte
)

func file_talon_v1_plugins_proto_rawDescGZIP() []byte {
	file_talon_v1_plugins_proto_rawDescOnce.Do(func() {
		file_talon_v1_plugins_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_talon_v1_plugins_proto_rawDesc), len(file_talon_v1_plugins_proto_rawDesc)))
	})
	return file_talon_v1_plugins_proto_rawDescData
}

var file_talon_v1_plugins_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_talon_v1_plugins_proto_goTypes = []any{
	(*DepsInstallRequest)(nil),   // 0: talon.v1.DepsInstallRequest
	(*DepsUninstallRequest)(nil), // 1: talon.v1.DepsUninstallRequest
	(*DepsDetailRequest)(nil),    // 2: talon.v1.DepsDetailRequest
	(*CommandsListRequest)(nil),  // 3: talon.v1.CommandsListRequest
	(*Empty)(nil),                // 4: talon.v1.Empty
	(*JSONPayload)(nil),          // 5: talon.v1.JSONPayload
}
var file_talon_v1_plugins_proto_depIdxs = []int32{
	4, // 0: talon.v1.PluginsService.DepsStatus:input_type -> talon.v1.Empty
	0, // 1: talon.v1.PluginsService.DepsInstall:input_type -> talon.v1.DepsInstallRequest
	1, // 2: talon.v1.PluginsService.DepsUninstall:input_type -> talon.v1.DepsUninstallRequest
	2, // 3: talon.v1.PluginsService.DepsDetail:input_type -> talon.v1.DepsDetailRequest
	3, // 4: talon.v1.PluginsService.CommandsList:input_type -> talon.v1.CommandsListRequest
	5, // 5: talon.v1.PluginsService.DepsStatus:output_type -> talon.v1.JSONPayload
	5, // 6: talon.v1.PluginsService.DepsInstall:output_type -> talon.v1.JSONPayload
	5, // 7: talon.v1.PluginsService.DepsUninstall:output_type -> talon.v1.JSONPayload
	5, // 8: talon.v1.PluginsService.DepsDetail:output_type -> talon.v1.JSONPayload
	5, // 9: talon.v1.PluginsService.CommandsList:output_type -> talon.v1.JSONPayload
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_talon_v1_plugins_proto_init() }
func file_talon_v1_plugins_proto_init() {
	if File_talon_v1_plugins_proto != nil {
		return
	}
	file_talon_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_talon_v1_plugins_proto_rawDesc), len(file_talon_v1_plugins_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_talon_v1_plugins_proto_goTypes,
		DependencyIndexes: file_talon_v1_plugins_proto_depIdxs,
		MessageInfos:      file_talon_v1_plugins_proto_msgTypes,
	}.Build()
	File_talon_v1_plugins_proto = out.File
	file_talon_v1_plugins_proto_goTypes = nil
	file_talon_v1_plugins_proto_depIdxs = nil
}
