// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: talon/v1/rpc.proto

package talonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DispatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Method name as registered on the gateway (e.g. "cron.list",
	// "secrets.reload"). Same shape the legacy WS path used.
	Method string `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	// Params is the JSON-encoded argument object for the handler;
	// empty means the method takes no args.
	ParamsJson    string `protobuf:"bytes,2,opt,name=params_json,json=paramsJson,proto3" json:"params_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchRequest) Reset() {
	*x = DispatchRequest{}
	mi := &file_talon_v1_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchRequest) ProtoMessage() {}

func (x *DispatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_talon_v1_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchRequest.ProtoReflect.Descriptor instead.
func (*DispatchRequest) Descriptor() ([]byte, []int) {
	return file_talon_v1_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *DispatchRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *DispatchRequest) GetParamsJson() string {
	if x != nil {
		return x.ParamsJson
	}
	return ""
}

type DispatchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Result is the JSON-encoded handler return value. Empty for
	// methods that return nothing. Errors come back as Connect
	// status codes (InvalidArgument, Unauthenticated, NotFound,
	// Internal) and never reach this field.
	ResultJson    string `protobuf:"bytes,1,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchResponse) Reset() {
	*x = DispatchResponse{}
	mi := &file_talon_v1_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchResponse) ProtoMessage() {}

func (x *DispatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_talon_v1_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchResponse.ProtoReflect.Descriptor instead.
func (*DispatchResponse) Descriptor() ([]byte, []int) {
	return file_talon_v1_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *DispatchResponse) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

var File_talon_v1_rpc_proto protoreflect.FileDescriptor

const file_talon_v1_rpc_proto_rawDesc = "" +
	"\n" +
	"\x12talon/v1/rpc.proto\x12\btalon.v1\x1a\x15talon/v1/common.proto\"J\n" +
	"\x0fDispatchRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x1f\n" +
	"\vparams_json\x18\x02 \x01(\tR\n" +
	"paramsJson\"3\n" +
	"\x10DispatchResponse\x12\x1f\n" +
	"\vresult_json\x18\x01 \x01(\tR\n" +
	"resultJson2O\n" +
	"\n" +
	"RpcService\x12A\n" +
	"\bDispatch\x12\x19.talon.v1.DispatchRequest\x1a\x1a.talon.v1.DispatchResponseB>Z<github.com/guygrigsby/talon/internal/api/v1/talon/v1;talonv1b\x06proto3"

var (
	file_talon_v1_rpc_proto_rawDescOnce sync.Once
	file_talon_v1_rpc_proto_rawDescData []byte
)

func file_talon_v1_rpc_proto_rawDescGZIP() []byte {
	file_talon_v1_rpc_proto_rawDescOnce.Do(func() {
		file_talon_v1_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_talon_v1_rpc_proto_rawDesc), len(file_talon_v1_rpc_proto_rawDesc)))
	})
	return file_talon_v1_rpc_proto_rawDescData
}

var file_talon_v1_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_talon_v1_rpc_proto_goTypes = []any{
	(*DispatchRequest)(nil),  // 0: talon.v1.DispatchRequest
	(*DispatchResponse)(nil), // 1: talon.v1.DispatchResponse
}
var file_talon_v1_rpc_proto_depIdxs = []int32{
	0, // 0: talon.v1.RpcService.Dispatch:input_type -> talon.v1.DispatchRequest
	1, // 1: talon.v1.RpcService.Dispatch:output_type -> talon.v1.DispatchResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_talon_v1_rpc_proto_init() }
func file_talon_v1_rpc_proto_init() {
	if File_talon_v1_rpc_proto != nil {
		return
	}
	file_talon_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_talon_v1_rpc_proto_rawDesc), len(file_talon_v1_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_talon_v1_rpc_proto_goTypes,
		DependencyIndexes: file_talon_v1_rpc_proto_depIdxs,
		MessageInfos:      file_talon_v1_rpc_proto_msgTypes,
	}.Build()
	File_talon_v1_rpc_proto = out.File
	file_talon_v1_rpc_proto_goTypes = nil
	file_talon_v1_rpc_proto_depIdxs = nil
}
