// talon.plugin.v1 is the wire contract every native plugin implements to
// participate in talon-gateway. Two services:
//
//   service Plugin — host calls these on the plugin (ListTools, RunTool,
//                    StreamCompletion, StartChannel, etc).
//   service Host   — plugin calls these back on the host (GetConfig,
//                    ListAgents, RunSubagent, etc). Every Host method has
//                    an associated Capability the host gates against the
//                    plugin's effective capability set:
//                      effective(plugin, agent) =
//                        manifest.needs ∪ user.grants − user.denies
//
// First-cut goals:
//   - cover the surfaces talon already implements natively (tools,
//     providers, channels-in/out, memory, subagent, identity)
//   - keep capabilities a closed enum so the gating layer is simple
//     reflection over a static map
//   - leave room to add capabilities and methods without breaking
//     existing plugins (proto3 forward-compat)
//
// Out of scope for this proto: subprocess handshake protocol (port +
// auth-cookie negotiation), plugin manifest discovery on disk. Those are
// host-runtime concerns landed in talon-bql.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: plugin.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Capability is the closed set of host-side resources a plugin may
// request. The host enforces these at request time against the plugin's
// effective capability set. CAPABILITY_UNSPECIFIED is reserved as the
// proto3 zero value.
type Capability int32

const (
	Capability_CAPABILITY_UNSPECIFIED Capability = 0
	// --- reads ----------------------------------------------------------
	Capability_CAPABILITY_READ_CONFIG         Capability = 1
	Capability_CAPABILITY_READ_CHAT_HISTORY   Capability = 2
	Capability_CAPABILITY_READ_AGENT_IDENTITY Capability = 3
	Capability_CAPABILITY_LIST_AGENTS         Capability = 4
	Capability_CAPABILITY_LIST_SESSIONS       Capability = 5
	Capability_CAPABILITY_LIST_MODELS         Capability = 6
	// --- writes ---------------------------------------------------------
	Capability_CAPABILITY_APPEND_MEMORY Capability = 20
	Capability_CAPABILITY_PATCH_SESSION Capability = 21
	// --- active actions -------------------------------------------------
	Capability_CAPABILITY_RUN_SUBAGENT         Capability = 40
	Capability_CAPABILITY_SEND_CHANNEL_MESSAGE Capability = 41
)

// Enum value maps for Capability.
var (
	Capability_name = map[int32]string{
		0:  "CAPABILITY_UNSPECIFIED",
		1:  "CAPABILITY_READ_CONFIG",
		2:  "CAPABILITY_READ_CHAT_HISTORY",
		3:  "CAPABILITY_READ_AGENT_IDENTITY",
		4:  "CAPABILITY_LIST_AGENTS",
		5:  "CAPABILITY_LIST_SESSIONS",
		6:  "CAPABILITY_LIST_MODELS",
		20: "CAPABILITY_APPEND_MEMORY",
		21: "CAPABILITY_PATCH_SESSION",
		40: "CAPABILITY_RUN_SUBAGENT",
		41: "CAPABILITY_SEND_CHANNEL_MESSAGE",
	}
	Capability_value = map[string]int32{
		"CAPABILITY_UNSPECIFIED":          0,
		"CAPABILITY_READ_CONFIG":          1,
		"CAPABILITY_READ_CHAT_HISTORY":    2,
		"CAPABILITY_READ_AGENT_IDENTITY":  3,
		"CAPABILITY_LIST_AGENTS":          4,
		"CAPABILITY_LIST_SESSIONS":        5,
		"CAPABILITY_LIST_MODELS":          6,
		"CAPABILITY_APPEND_MEMORY":        20,
		"CAPABILITY_PATCH_SESSION":        21,
		"CAPABILITY_RUN_SUBAGENT":         40,
		"CAPABILITY_SEND_CHANNEL_MESSAGE": 41,
	}
)

func (x Capability) Enum() *Capability {
	p := new(Capability)
	*p = x
	return p
}

func (x Capability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Capability) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_enumTypes[0].Descriptor()
}

func (Capability) Type() protoreflect.EnumType {
	return &file_plugin_proto_enumTypes[0]
}

func (x Capability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Capability.Descriptor instead.
func (Capability) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

// Role mirrors provider.Role. ROLE_TOOL turns use tool_call_id to point
// at the originating assistant tool_use.
type Role int32

const (
	Role_ROLE_UNSPECIFIED Role = 0
	Role_ROLE_USER        Role = 1
	Role_ROLE_ASSISTANT   Role = 2
	Role_ROLE_SYSTEM      Role = 3
	Role_ROLE_TOOL        Role = 4
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_UNSPECIFIED",
		1: "ROLE_USER",
		2: "ROLE_ASSISTANT",
		3: "ROLE_SYSTEM",
		4: "ROLE_TOOL",
	}
	Role_value = map[string]int32{
		"ROLE_UNSPECIFIED": 0,
		"ROLE_USER":        1,
		"ROLE_ASSISTANT":   2,
		"ROLE_SYSTEM":      3,
		"ROLE_TOOL":        4,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_enumTypes[1].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_plugin_proto_enumTypes[1]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

// Manifest is the plugin's self-description. Returned from
// Plugin.Initialize and stored by the host for the lifetime of the
// plugin process. The "offers" half describes what the plugin makes
// available to the host (host calls these methods on the plugin); the
// "needs" half is the plugin's capability ask.
type Manifest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version     string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// What this plugin OFFERS to the host. Empty means the plugin doesn't
	// implement that surface.
	OffersTools     []*ToolSpec     `protobuf:"bytes,10,rep,name=offers_tools,json=offersTools,proto3" json:"offers_tools,omitempty"`
	OffersProviders []*ProviderSpec `protobuf:"bytes,11,rep,name=offers_providers,json=offersProviders,proto3" json:"offers_providers,omitempty"`
	OffersChannels  []string        `protobuf:"bytes,12,rep,name=offers_channels,json=offersChannels,proto3" json:"offers_channels,omitempty"` // e.g. ["telegram"]
	// What this plugin NEEDS from the host. The host gates each Host-side
	// method against this list (intersected with user grants/denies).
	Needs         []Capability `protobuf:"varint,20,rep,packed,name=needs,proto3,enum=talon.plugin.v1.Capability" json:"needs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manifest) Reset() {
	*x = Manifest{}
	mi := &file_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manifest) ProtoMessage() {}

func (x *Manifest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manifest.ProtoReflect.Descriptor instead.
func (*Manifest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *Manifest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Manifest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Manifest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Manifest) GetOffersTools() []*ToolSpec {
	if x != nil {
		return x.OffersTools
	}
	return nil
}

func (x *Manifest) GetOffersProviders() []*ProviderSpec {
	if x != nil {
		return x.OffersProviders
	}
	return nil
}

func (x *Manifest) GetOffersChannels() []string {
	if x != nil {
		return x.OffersChannels
	}
	return nil
}

func (x *Manifest) GetNeeds() []Capability {
	if x != nil {
		return x.Needs
	}
	return nil
}

// Message is one turn of conversation passed across the wire. Mirrors
// provider.Message.
type Message struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Role    Role                   `protobuf:"varint,1,opt,name=role,proto3,enum=talon.plugin.v1.Role" json:"role,omitempty"`
	Content string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// Assistant turns invoking tools carry these. Empty for plain text turns.
	ToolCalls []*ToolCall `protobuf:"bytes,3,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	// ROLE_TOOL only — id of the assistant tool_use this is the result for.
	ToolCallId    string `protobuf:"bytes,4,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNSPECIFIED
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetToolCalls() []*ToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

func (x *Message) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

type ToolCall struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// JSON-encoded arguments. The receiving side decodes per the tool's
	// ParametersSchema.
	ArgumentsJson string `protobuf:"bytes,3,opt,name=arguments_json,json=argumentsJson,proto3" json:"arguments_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *ToolCall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolCall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolCall) GetArgumentsJson() string {
	if x != nil {
		return x.ArgumentsJson
	}
	return ""
}

type ToolSpec struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// JSON schema bytes (verbatim) — host passes these through to the
	// provider's tools advertisement, plugin authors don't need a special
	// protobuf representation for arbitrary JSON schemas.
	ParametersSchema []byte `protobuf:"bytes,3,opt,name=parameters_schema,json=parametersSchema,proto3" json:"parameters_schema,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ToolSpec) Reset() {
	*x = ToolSpec{}
	mi := &file_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolSpec) ProtoMessage() {}

func (x *ToolSpec) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolSpec.ProtoReflect.Descriptor instead.
func (*ToolSpec) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *ToolSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolSpec) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolSpec) GetParametersSchema() []byte {
	if x != nil {
		return x.ParametersSchema
	}
	return nil
}

type ProviderSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Provider key, must match the ModelID provider segment ("openai",
	// "deepseek", etc.).
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Concrete model ids this provider serves. If empty, the host treats
	// the provider as accepting any model (caller-validated). For
	// multi-tenant plugins this often stays empty in the manifest and
	// the host calls Plugin.ListProviderModels at request time to get
	// a live list (with per-plugin caching).
	Models        []string `protobuf:"bytes,2,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderSpec) Reset() {
	*x = ProviderSpec{}
	mi := &file_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderSpec) ProtoMessage() {}

func (x *ProviderSpec) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderSpec.ProtoReflect.Descriptor instead.
func (*ProviderSpec) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *ProviderSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProviderSpec) GetModels() []string {
	if x != nil {
		return x.Models
	}
	return nil
}

// ModelDescriptor is one row in a ListProviderModelsResponse. Fields
// mirror what models.list emits over the wire so the host can pass
// them through with no per-provider munging. Empty/zero values mean
// "not advertised" — the FE renders the column conditionally.
type ModelDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ContextWindow int64                  `protobuf:"varint,3,opt,name=context_window,json=contextWindow,proto3" json:"context_window,omitempty"`
	Reasoning     bool                   `protobuf:"varint,4,opt,name=reasoning,proto3" json:"reasoning,omitempty"`
	// Input modalities — typically ["text"] or ["text","image"].
	Input         []string `protobuf:"bytes,5,rep,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelDescriptor) Reset() {
	*x = ModelDescriptor{}
	mi := &file_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelDescriptor) ProtoMessage() {}

func (x *ModelDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelDescriptor.ProtoReflect.Descriptor instead.
func (*ModelDescriptor) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *ModelDescriptor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ModelDescriptor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModelDescriptor) GetContextWindow() int64 {
	if x != nil {
		return x.ContextWindow
	}
	return 0
}

func (x *ModelDescriptor) GetReasoning() bool {
	if x != nil {
		return x.Reasoning
	}
	return false
}

func (x *ModelDescriptor) GetInput() []string {
	if x != nil {
		return x.Input
	}
	return nil
}

// Delta is one event in a streaming completion. Mirrors provider.Delta;
// only one oneof variant is set per message.
type Delta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Delta_Text
	//	*Delta_Reasoning
	//	*Delta_Usage
	//	*Delta_ToolCall
	//	*Delta_Error
	Kind          isDelta_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Delta) Reset() {
	*x = Delta{}
	mi := &file_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delta) ProtoMessage() {}

func (x *Delta) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delta.ProtoReflect.Descriptor instead.
func (*Delta) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *Delta) GetKind() isDelta_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Delta) GetText() string {
	if x != nil {
		if x, ok := x.Kind.(*Delta_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *Delta) GetReasoning() string {
	if x != nil {
		if x, ok := x.Kind.(*Delta_Reasoning); ok {
			return x.Reasoning
		}
	}
	return ""
}

func (x *Delta) GetUsage() *Usage {
	if x != nil {
		if x, ok := x.Kind.(*Delta_Usage); ok {
			return x.Usage
		}
	}
	return nil
}

func (x *Delta) GetToolCall() *ToolCall {
	if x != nil {
		if x, ok := x.Kind.(*Delta_ToolCall); ok {
			return x.ToolCall
		}
	}
	return nil
}

func (x *Delta) GetError() string {
	if x != nil {
		if x, ok := x.Kind.(*Delta_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isDelta_Kind interface {
	isDelta_Kind()
}

type Delta_Text struct {
	Text string `protobuf:"bytes,1,opt,name=text,proto3,oneof"` // visible token chunk
}

type Delta_Reasoning struct {
	Reasoning string `protobuf:"bytes,2,opt,name=reasoning,proto3,oneof"` // hidden reasoning trace (o1/Claude-thinking)
}

type Delta_Usage struct {
	Usage *Usage `protobuf:"bytes,3,opt,name=usage,proto3,oneof"` // sent at most once near end-of-stream
}

type Delta_ToolCall struct {
	ToolCall *ToolCall `protobuf:"bytes,4,opt,name=tool_call,json=toolCall,proto3,oneof"` // assembled tool call (provider buffers fragments internally)
}

type Delta_Error struct {
	Error string `protobuf:"bytes,5,opt,name=error,proto3,oneof"` // mid-stream failure; channel closes after
}

func (*Delta_Text) isDelta_Kind() {}

func (*Delta_Reasoning) isDelta_Kind() {}

func (*Delta_Usage) isDelta_Kind() {}

func (*Delta_ToolCall) isDelta_Kind() {}

func (*Delta_Error) isDelta_Kind() {}

type Usage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	InputTokens     int32                  `protobuf:"varint,1,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens    int32                  `protobuf:"varint,2,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	ReasoningTokens int32                  `protobuf:"varint,3,opt,name=reasoning_tokens,json=reasoningTokens,proto3" json:"reasoning_tokens,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Usage) Reset() {
	*x = Usage{}
	mi := &file_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usage.ProtoReflect.Descriptor instead.
func (*Usage) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *Usage) GetInputTokens() int32 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *Usage) GetOutputTokens() int32 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *Usage) GetReasoningTokens() int32 {
	if x != nil {
		return x.ReasoningTokens
	}
	return 0
}

type InitializeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Auth cookie negotiated during the deprecated pre-go-plugin subprocess
	// handshake. The native go-plugin host uses connection identity captured
	// at GRPCBroker.AcceptAndServe time instead.
	//
	// Deprecated: Marked as deprecated in plugin.proto.
	AuthCookie string `protobuf:"bytes,1,opt,name=auth_cookie,json=authCookie,proto3" json:"auth_cookie,omitempty"`
	// Address (host:port) of the host's Host-service. DEPRECATED — see
	// above. Native plugins dial back via host_broker_id.
	//
	// Deprecated: Marked as deprecated in plugin.proto.
	HostAddress string `protobuf:"bytes,2,opt,name=host_address,json=hostAddress,proto3" json:"host_address,omitempty"`
	// GRPCBroker id the plugin dials back to reach the host's Host
	// service over the existing gRPC connection. Populated by the
	// native host (talon-e4h); zero on the direct provider path.
	HostBrokerId  int64 `protobuf:"varint,3,opt,name=host_broker_id,json=hostBrokerId,proto3" json:"host_broker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeRequest) Reset() {
	*x = InitializeRequest{}
	mi := &file_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeRequest) ProtoMessage() {}

func (x *InitializeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeRequest.ProtoReflect.Descriptor instead.
func (*InitializeRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{8}
}

// Deprecated: Marked as deprecated in plugin.proto.
func (x *InitializeRequest) GetAuthCookie() string {
	if x != nil {
		return x.AuthCookie
	}
	return ""
}

// Deprecated: Marked as deprecated in plugin.proto.
func (x *InitializeRequest) GetHostAddress() string {
	if x != nil {
		return x.HostAddress
	}
	return ""
}

func (x *InitializeRequest) GetHostBrokerId() int64 {
	if x != nil {
		return x.HostBrokerId
	}
	return 0
}

type InitializeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manifest      *Manifest              `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeResponse) Reset() {
	*x = InitializeResponse{}
	mi := &file_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeResponse) ProtoMessage() {}

func (x *InitializeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeResponse.ProtoReflect.Descriptor instead.
func (*InitializeResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *InitializeResponse) GetManifest() *Manifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{10}
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{11}
}

type RunToolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolName      string                 `protobuf:"bytes,1,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ArgumentsJson string                 `protobuf:"bytes,2,opt,name=arguments_json,json=argumentsJson,proto3" json:"arguments_json,omitempty"`
	// The agent context this invocation belongs to. Per-agent grants may
	// widen or narrow the plugin's authority for this call.
	AgentId string `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// The chat runId — plugins use this to correlate back-channel calls
	// (e.g. emitting tool-stream progress updates) with the parent run.
	RunId         string `protobuf:"bytes,4,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunToolRequest) Reset() {
	*x = RunToolRequest{}
	mi := &file_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunToolRequest) ProtoMessage() {}

func (x *RunToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunToolRequest.ProtoReflect.Descriptor instead.
func (*RunToolRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *RunToolRequest) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *RunToolRequest) GetArgumentsJson() string {
	if x != nil {
		return x.ArgumentsJson
	}
	return ""
}

func (x *RunToolRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RunToolRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type RunToolResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Output string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	// Set true when the tool ran but the operation failed (model-visible
	// error). Transport-level failures should propagate as a gRPC status,
	// not via this flag.
	IsError       bool `protobuf:"varint,2,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunToolResponse) Reset() {
	*x = RunToolResponse{}
	mi := &file_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunToolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunToolResponse) ProtoMessage() {}

func (x *RunToolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunToolResponse.ProtoReflect.Descriptor instead.
func (*RunToolResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *RunToolResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *RunToolResponse) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

type StreamCompletionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Model id WITHOUT the provider prefix (e.g. "gpt-5.4-mini") — the
	// routing already picked this provider, so the prefix is implicit
	// for single-provider plugins. Multi-tenant plugins (one process
	// serving multiple providers) need the provider name too — see
	// the `provider` field below.
	Model    string      `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	System   string      `protobuf:"bytes,2,opt,name=system,proto3" json:"system,omitempty"`
	Messages []*Message  `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`
	Tools    []*ToolSpec `protobuf:"bytes,4,rep,name=tools,proto3" json:"tools,omitempty"`
	// Generation options. Optional fields use proto3 explicit-presence so
	// unset stays distinct from zero.
	Temperature     *float64 `protobuf:"fixed64,10,opt,name=temperature,proto3,oneof" json:"temperature,omitempty"`
	MaxOutputTokens int32    `protobuf:"varint,11,opt,name=max_output_tokens,json=maxOutputTokens,proto3" json:"max_output_tokens,omitempty"`
	// Provider name the host routed to (matches one of the plugin's
	// Manifest.OffersProviders entries). Populated by the host so
	// multi-tenant plugins (e.g. openai-compat serving openai +
	// deepseek + mistral) can pick the right backend. Single-provider
	// plugins can ignore this — it's redundant with their identity.
	Provider      string `protobuf:"bytes,12,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamCompletionRequest) Reset() {
	*x = StreamCompletionRequest{}
	mi := &file_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamCompletionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamCompletionRequest) ProtoMessage() {}

func (x *StreamCompletionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamCompletionRequest.ProtoReflect.Descriptor instead.
func (*StreamCompletionRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *StreamCompletionRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *StreamCompletionRequest) GetSystem() string {
	if x != nil {
		return x.System
	}
	return ""
}

func (x *StreamCompletionRequest) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *StreamCompletionRequest) GetTools() []*ToolSpec {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *StreamCompletionRequest) GetTemperature() float64 {
	if x != nil && x.Temperature != nil {
		return *x.Temperature
	}
	return 0
}

func (x *StreamCompletionRequest) GetMaxOutputTokens() int32 {
	if x != nil {
		return x.MaxOutputTokens
	}
	return 0
}

func (x *StreamCompletionRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type ListProviderModelsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Provider name to enumerate. Multi-tenant plugins (e.g.
	// openai-compat) read this to pick the right backend; single-
	// provider plugins (e.g. anthropic) can ignore it.
	Provider string `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	// When true, the plugin should bypass its cache and re-query the
	// upstream. Off by default to keep models.list fast.
	Refresh       bool `protobuf:"varint,2,opt,name=refresh,proto3" json:"refresh,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProviderModelsRequest) Reset() {
	*x = ListProviderModelsRequest{}
	mi := &file_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProviderModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProviderModelsRequest) ProtoMessage() {}

func (x *ListProviderModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProviderModelsRequest.ProtoReflect.Descriptor instead.
func (*ListProviderModelsRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *ListProviderModelsRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ListProviderModelsRequest) GetRefresh() bool {
	if x != nil {
		return x.Refresh
	}
	return false
}

type ListProviderModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*ModelDescriptor     `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProviderModelsResponse) Reset() {
	*x = ListProviderModelsResponse{}
	mi := &file_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProviderModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProviderModelsResponse) ProtoMessage() {}

func (x *ListProviderModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProviderModelsResponse.ProtoReflect.Descriptor instead.
func (*ListProviderModelsResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{16}
}

func (x *ListProviderModelsResponse) GetModels() []*ModelDescriptor {
	if x != nil {
		return x.Models
	}
	return nil
}

type StartChannelRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ChannelName string                 `protobuf:"bytes,1,opt,name=channel_name,json=channelName,proto3" json:"channel_name,omitempty"`
	// Channel-specific config tree (JSON bytes from the relevant
	// channels.<name> sub-tree). Plugin parses per its own schema.
	ChannelConfig []byte `protobuf:"bytes,2,opt,name=channel_config,json=channelConfig,proto3" json:"channel_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartChannelRequest) Reset() {
	*x = StartChannelRequest{}
	mi := &file_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartChannelRequest) ProtoMessage() {}

func (x *StartChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartChannelRequest.ProtoReflect.Descriptor instead.
func (*StartChannelRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{17}
}

func (x *StartChannelRequest) GetChannelName() string {
	if x != nil {
		return x.ChannelName
	}
	return ""
}

func (x *StartChannelRequest) GetChannelConfig() []byte {
	if x != nil {
		return x.ChannelConfig
	}
	return nil
}

type IncomingChannelMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       string                 `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	SenderId      string                 `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"` // platform user id
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	RoomId        string                 `protobuf:"bytes,4,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"` // group/channel id; empty for direct
	Text          string                 `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	TsMs          int64                  `protobuf:"varint,6,opt,name=ts_ms,json=tsMs,proto3" json:"ts_ms,omitempty"` // unix-millis the platform reported
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncomingChannelMessage) Reset() {
	*x = IncomingChannelMessage{}
	mi := &file_plugin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncomingChannelMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncomingChannelMessage) ProtoMessage() {}

func (x *IncomingChannelMessage) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncomingChannelMessage.ProtoReflect.Descriptor instead.
func (*IncomingChannelMessage) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{18}
}

func (x *IncomingChannelMessage) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *IncomingChannelMessage) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *IncomingChannelMessage) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *IncomingChannelMessage) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *IncomingChannelMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *IncomingChannelMessage) GetTsMs() int64 {
	if x != nil {
		return x.TsMs
	}
	return 0
}

type SendChannelMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       string                 `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"` // target room/sender for direct reply
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendChannelMessageRequest) Reset() {
	*x = SendChannelMessageRequest{}
	mi := &file_plugin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendChannelMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendChannelMessageRequest) ProtoMessage() {}

func (x *SendChannelMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendChannelMessageRequest.ProtoReflect.Descriptor instead.
func (*SendChannelMessageRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{19}
}

func (x *SendChannelMessageRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *SendChannelMessageRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SendChannelMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SendChannelMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendChannelMessageResponse) Reset() {
	*x = SendChannelMessageResponse{}
	mi := &file_plugin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendChannelMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendChannelMessageResponse) ProtoMessage() {}

func (x *SendChannelMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendChannelMessageResponse.ProtoReflect.Descriptor instead.
func (*SendChannelMessageResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{20}
}

func (x *SendChannelMessageResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type GetConfigRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional dot-path scope (e.g. "channels.telegram"). Empty returns
	// the whole config the plugin is allowed to see. The host applies
	// secret redaction the same way config.get does, plus any user-grant
	// scoping that further narrows access.
	Path          string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_plugin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{21}
}

func (x *GetConfigRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type GetConfigResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON value at the requested path. Bytes (not a structured proto)
	// because config is arbitrary user JSON.
	RawJson       []byte `protobuf:"bytes,1,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_plugin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{22}
}

func (x *GetConfigResponse) GetRawJson() []byte {
	if x != nil {
		return x.RawJson
	}
	return nil
}

type ListAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_plugin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{23}
}

type ListAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawJson       []byte                 `protobuf:"bytes,1,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"` // JSON envelope (see agents.list)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_plugin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{24}
}

func (x *ListAgentsResponse) GetRawJson() []byte {
	if x != nil {
		return x.RawJson
	}
	return nil
}

type GetAgentIdentityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentIdentityRequest) Reset() {
	*x = GetAgentIdentityRequest{}
	mi := &file_plugin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentIdentityRequest) ProtoMessage() {}

func (x *GetAgentIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentIdentityRequest.ProtoReflect.Descriptor instead.
func (*GetAgentIdentityRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{25}
}

func (x *GetAgentIdentityRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type GetAgentIdentityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Emoji         string                 `protobuf:"bytes,3,opt,name=emoji,proto3" json:"emoji,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentIdentityResponse) Reset() {
	*x = GetAgentIdentityResponse{}
	mi := &file_plugin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentIdentityResponse) ProtoMessage() {}

func (x *GetAgentIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentIdentityResponse.ProtoReflect.Descriptor instead.
func (*GetAgentIdentityResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{26}
}

func (x *GetAgentIdentityResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *GetAgentIdentityResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetAgentIdentityResponse) GetEmoji() string {
	if x != nil {
		return x.Emoji
	}
	return ""
}

func (x *GetAgentIdentityResponse) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type ListModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsRequest) Reset() {
	*x = ListModelsRequest{}
	mi := &file_plugin_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRequest) ProtoMessage() {}

func (x *ListModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsRequest.ProtoReflect.Descriptor instead.
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{27}
}

type ListModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawJson       []byte                 `protobuf:"bytes,1,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsResponse) Reset() {
	*x = ListModelsResponse{}
	mi := &file_plugin_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsResponse) ProtoMessage() {}

func (x *ListModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsResponse.ProtoReflect.Descriptor instead.
func (*ListModelsResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{28}
}

func (x *ListModelsResponse) GetRawJson() []byte {
	if x != nil {
		return x.RawJson
	}
	return nil
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_plugin_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{29}
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawJson       []byte                 `protobuf:"bytes,1,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_plugin_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{30}
}

func (x *ListSessionsResponse) GetRawJson() []byte {
	if x != nil {
		return x.RawJson
	}
	return nil
}

type GetChatHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionKey    string                 `protobuf:"bytes,1,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"` // 0 = no limit
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatHistoryRequest) Reset() {
	*x = GetChatHistoryRequest{}
	mi := &file_plugin_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatHistoryRequest) ProtoMessage() {}

func (x *GetChatHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetChatHistoryRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{31}
}

func (x *GetChatHistoryRequest) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

func (x *GetChatHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetChatHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawJson       []byte                 `protobuf:"bytes,1,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatHistoryResponse) Reset() {
	*x = GetChatHistoryResponse{}
	mi := &file_plugin_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatHistoryResponse) ProtoMessage() {}

func (x *GetChatHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetChatHistoryResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{32}
}

func (x *GetChatHistoryResponse) GetRawJson() []byte {
	if x != nil {
		return x.RawJson
	}
	return nil
}

type AppendMemoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendMemoryRequest) Reset() {
	*x = AppendMemoryRequest{}
	mi := &file_plugin_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendMemoryRequest) ProtoMessage() {}

func (x *AppendMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendMemoryRequest.ProtoReflect.Descriptor instead.
func (*AppendMemoryRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{33}
}

func (x *AppendMemoryRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AppendMemoryRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type AppendMemoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendMemoryResponse) Reset() {
	*x = AppendMemoryResponse{}
	mi := &file_plugin_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendMemoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendMemoryResponse) ProtoMessage() {}

func (x *AppendMemoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendMemoryResponse.ProtoReflect.Descriptor instead.
func (*AppendMemoryResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{34}
}

func (x *AppendMemoryResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type RunSubagentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Prompt        string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunSubagentRequest) Reset() {
	*x = RunSubagentRequest{}
	mi := &file_plugin_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunSubagentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunSubagentRequest) ProtoMessage() {}

func (x *RunSubagentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunSubagentRequest.ProtoReflect.Descriptor instead.
func (*RunSubagentRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{35}
}

func (x *RunSubagentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RunSubagentRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type RunSubagentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunSubagentResponse) Reset() {
	*x = RunSubagentResponse{}
	mi := &file_plugin_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunSubagentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunSubagentResponse) ProtoMessage() {}

func (x *RunSubagentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunSubagentResponse.ProtoReflect.Descriptor instead.
func (*RunSubagentResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{36}
}

func (x *RunSubagentResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_plugin_proto protoreflect.FileDescriptor

const file_plugin_proto_rawDesc = "" +
	"\n" +
	"\fplugin.proto\x12\x0ftalon.plugin.v1\"\xc4\x02\n" +
	"\bManifest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12<\n" +
	"\foffers_tools\x18\n" +
	" \x03(\v2\x19.talon.plugin.v1.ToolSpecR\voffersTools\x12H\n" +
	"\x10offers_providers\x18\v \x03(\v2\x1d.talon.plugin.v1.ProviderSpecR\x0foffersProviders\x12'\n" +
	"\x0foffers_channels\x18\f \x03(\tR\x0eoffersChannels\x121\n" +
	"\x05needs\x18\x14 \x03(\x0e2\x1b.talon.plugin.v1.CapabilityR\x05needsJ\x04\b\r\x10\x0e\"\xaa\x01\n" +
	"\aMessage\x12)\n" +
	"\x04role\x18\x01 \x01(\x0e2\x15.talon.plugin.v1.RoleR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x128\n" +
	"\n" +
	"tool_calls\x18\x03 \x03(\v2\x19.talon.plugin.v1.ToolCallR\ttoolCalls\x12 \n" +
	"\ftool_call_id\x18\x04 \x01(\tR\n" +
	"toolCallId\"U\n" +
	"\bToolCall\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x0earguments_json\x18\x03 \x01(\tR\rargumentsJson\"m\n" +
	"\bToolSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12+\n" +
	"\x11parameters_schema\x18\x03 \x01(\fR\x10parametersSchema\":\n" +
	"\fProviderSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06models\x18\x02 \x03(\tR\x06models\"\x90\x01\n" +
	"\x0fModelDescriptor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x0econtext_window\x18\x03 \x01(\x03R\rcontextWindow\x12\x1c\n" +
	"\treasoning\x18\x04 \x01(\bR\treasoning\x12\x14\n" +
	"\x05input\x18\x05 \x03(\tR\x05input\"\xc7\x01\n" +
	"\x05Delta\x12\x14\n" +
	"\x04text\x18\x01 \x01(\tH\x00R\x04text\x12\x1e\n" +
	"\treasoning\x18\x02 \x01(\tH\x00R\treasoning\x12.\n" +
	"\x05usage\x18\x03 \x01(\v2\x16.talon.plugin.v1.UsageH\x00R\x05usage\x128\n" +
	"\ttool_call\x18\x04 \x01(\v2\x19.talon.plugin.v1.ToolCallH\x00R\btoolCall\x12\x16\n" +
	"\x05error\x18\x05 \x01(\tH\x00R\x05errorB\x06\n" +
	"\x04kind\"z\n" +
	"\x05Usage\x12!\n" +
	"\finput_tokens\x18\x01 \x01(\x05R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x02 \x01(\x05R\foutputTokens\x12)\n" +
	"\x10reasoning_tokens\x18\x03 \x01(\x05R\x0freasoningTokens\"\x85\x01\n" +
	"\x11InitializeRequest\x12#\n" +
	"\vauth_cookie\x18\x01 \x01(\tB\x02\x18\x01R\n" +
	"authCookie\x12%\n" +
	"\fhost_address\x18\x02 \x01(\tB\x02\x18\x01R\vhostAddress\x12$\n" +
	"\x0ehost_broker_id\x18\x03 \x01(\x03R\fhostBrokerId\"K\n" +
	"\x12InitializeResponse\x125\n" +
	"\bmanifest\x18\x01 \x01(\v2\x19.talon.plugin.v1.ManifestR\bmanifest\"\x11\n" +
	"\x0fShutdownRequest\"\x12\n" +
	"\x10ShutdownResponse\"\x86\x01\n" +
	"\x0eRunToolRequest\x12\x1b\n" +
	"\ttool_name\x18\x01 \x01(\tR\btoolName\x12%\n" +
	"\x0earguments_json\x18\x02 \x01(\tR\rargumentsJson\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12\x15\n" +
	"\x06run_id\x18\x04 \x01(\tR\x05runId\"D\n" +
	"\x0fRunToolResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\x12\x19\n" +
	"\bis_error\x18\x02 \x01(\bR\aisError\"\xad\x02\n" +
	"\x17StreamCompletionRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x16\n" +
	"\x06system\x18\x02 \x01(\tR\x06system\x124\n" +
	"\bmessages\x18\x03 \x03(\v2\x18.talon.plugin.v1.MessageR\bmessages\x12/\n" +
	"\x05tools\x18\x04 \x03(\v2\x19.talon.plugin.v1.ToolSpecR\x05tools\x12%\n" +
	"\vtemperature\x18\n" +
	" \x01(\x01H\x00R\vtemperature\x88\x01\x01\x12*\n" +
	"\x11max_output_tokens\x18\v \x01(\x05R\x0fmaxOutputTokens\x12\x1a\n" +
	"\bprovider\x18\f \x01(\tR\bproviderB\x0e\n" +
	"\f_temperature\"Q\n" +
	"\x19ListProviderModelsRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x18\n" +
	"\arefresh\x18\x02 \x01(\bR\arefresh\"V\n" +
	"\x1aListProviderModelsResponse\x128\n" +
	"\x06models\x18\x01 \x03(\v2 .talon.plugin.v1.ModelDescriptorR\x06models\"_\n" +
	"\x13StartChannelRequest\x12!\n" +
	"\fchannel_name\x18\x01 \x01(\tR\vchannelName\x12%\n" +
	"\x0echannel_config\x18\x02 \x01(\fR\rchannelConfig\"\xb4\x01\n" +
	"\x16IncomingChannelMessage\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x17\n" +
	"\aroom_id\x18\x04 \x01(\tR\x06roomId\x12\x12\n" +
	"\x04text\x18\x05 \x01(\tR\x04text\x12\x13\n" +
	"\x05ts_ms\x18\x06 \x01(\x03R\x04tsMs\"b\n" +
	"\x19SendChannelMessageRequest\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\",\n" +
	"\x1aSendChannelMessageResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"&\n" +
	"\x10GetConfigRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\".\n" +
	"\x11GetConfigResponse\x12\x19\n" +
	"\braw_json\x18\x01 \x01(\fR\arawJson\"\x13\n" +
	"\x11ListAgentsRequest\"/\n" +
	"\x12ListAgentsResponse\x12\x19\n" +
	"\braw_json\x18\x01 \x01(\fR\arawJson\"4\n" +
	"\x17GetAgentIdentityRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"w\n" +
	"\x18GetAgentIdentityResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05emoji\x18\x03 \x01(\tR\x05emoji\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\"\x13\n" +
	"\x11ListModelsRequest\"/\n" +
	"\x12ListModelsResponse\x12\x19\n" +
	"\braw_json\x18\x01 \x01(\fR\arawJson\"\x15\n" +
	"\x13ListSessionsRequest\"1\n" +
	"\x14ListSessionsResponse\x12\x19\n" +
	"\braw_json\x18\x01 \x01(\fR\arawJson\"N\n" +
	"\x15GetChatHistoryRequest\x12\x1f\n" +
	"\vsession_key\x18\x01 \x01(\tR\n" +
	"sessionKey\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"3\n" +
	"\x16GetChatHistoryResponse\x12\x19\n" +
	"\braw_json\x18\x01 \x01(\fR\arawJson\"D\n" +
	"\x13AppendMemoryRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"&\n" +
	"\x14AppendMemoryResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"G\n" +
	"\x12RunSubagentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\")\n" +
	"\x13RunSubagentResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text*\xde\x02\n" +
	"\n" +
	"Capability\x12\x1a\n" +
	"\x16CAPABILITY_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16CAPABILITY_READ_CONFIG\x10\x01\x12 \n" +
	"\x1cCAPABILITY_READ_CHAT_HISTORY\x10\x02\x12\"\n" +
	"\x1eCAPABILITY_READ_AGENT_IDENTITY\x10\x03\x12\x1a\n" +
	"\x16CAPABILITY_LIST_AGENTS\x10\x04\x12\x1c\n" +
	"\x18CAPABILITY_LIST_SESSIONS\x10\x05\x12\x1a\n" +
	"\x16CAPABILITY_LIST_MODELS\x10\x06\x12\x1c\n" +
	"\x18CAPABILITY_APPEND_MEMORY\x10\x14\x12\x1c\n" +
	"\x18CAPABILITY_PATCH_SESSION\x10\x15\x12\x1b\n" +
	"\x17CAPABILITY_RUN_SUBAGENT\x10(\x12#\n" +
	"\x1fCAPABILITY_SEND_CHANNEL_MESSAGE\x10)*_\n" +
	"\x04Role\x12\x14\n" +
	"\x10ROLE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tROLE_USER\x10\x01\x12\x12\n" +
	"\x0eROLE_ASSISTANT\x10\x02\x12\x0f\n" +
	"\vROLE_SYSTEM\x10\x03\x12\r\n" +
	"\tROLE_TOOL\x10\x042\x95\x05\n" +
	"\x06Plugin\x12U\n" +
	"\n" +
	"Initialize\x12\".talon.plugin.v1.InitializeRequest\x1a#.talon.plugin.v1.InitializeResponse\x12O\n" +
	"\bShutdown\x12 .talon.plugin.v1.ShutdownRequest\x1a!.talon.plugin.v1.ShutdownResponse\x12L\n" +
	"\aRunTool\x12\x1f.talon.plugin.v1.RunToolRequest\x1a .talon.plugin.v1.RunToolResponse\x12V\n" +
	"\x10StreamCompletion\x12(.talon.plugin.v1.StreamCompletionRequest\x1a\x16.talon.plugin.v1.Delta0\x01\x12m\n" +
	"\x12ListProviderModels\x12*.talon.plugin.v1.ListProviderModelsRequest\x1a+.talon.plugin.v1.ListProviderModelsResponse\x12_\n" +
	"\fStartChannel\x12$.talon.plugin.v1.StartChannelRequest\x1a'.talon.plugin.v1.IncomingChannelMessage0\x01\x12m\n" +
	"\x12SendChannelMessage\x12*.talon.plugin.v1.SendChannelMessageRequest\x1a+.talon.plugin.v1.SendChannelMessageResponse2\xe8\x05\n" +
	"\x04Host\x12R\n" +
	"\tGetConfig\x12!.talon.plugin.v1.GetConfigRequest\x1a\".talon.plugin.v1.GetConfigResponse\x12U\n" +
	"\n" +
	"ListAgents\x12\".talon.plugin.v1.ListAgentsRequest\x1a#.talon.plugin.v1.ListAgentsResponse\x12g\n" +
	"\x10GetAgentIdentity\x12(.talon.plugin.v1.GetAgentIdentityRequest\x1a).talon.plugin.v1.GetAgentIdentityResponse\x12U\n" +
	"\n" +
	"ListModels\x12\".talon.plugin.v1.ListModelsRequest\x1a#.talon.plugin.v1.ListModelsResponse\x12[\n" +
	"\fListSessions\x12$.talon.plugin.v1.ListSessionsRequest\x1a%.talon.plugin.v1.ListSessionsResponse\x12a\n" +
	"\x0eGetChatHistory\x12&.talon.plugin.v1.GetChatHistoryRequest\x1a'.talon.plugin.v1.GetChatHistoryResponse\x12[\n" +
	"\fAppendMemory\x12$.talon.plugin.v1.AppendMemoryRequest\x1a%.talon.plugin.v1.AppendMemoryResponse\x12X\n" +
	"\vRunSubagent\x12#.talon.plugin.v1.RunSubagentRequest\x1a$.talon.plugin.v1.RunSubagentResponseB3Z1github.com/guygrigsby/talon/internal/plugin/pb;pbb\x06proto3"

var (
	file_plugin_proto_rawDescOnce sync.Once
	file_plugin_proto_rawDescData []byte
)

func file_plugin_proto_rawDescGZIP() []byte {
	file_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)))
	})
	return file_plugin_proto_rawDescData
}

var file_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_plugin_proto_goTypes = []any{
	(Capability)(0),                    // 0: talon.plugin.v1.Capability
	(Role)(0),                          // 1: talon.plugin.v1.Role
	(*Manifest)(nil),                   // 2: talon.plugin.v1.Manifest
	(*Message)(nil),                    // 3: talon.plugin.v1.Message
	(*ToolCall)(nil),                   // 4: talon.plugin.v1.ToolCall
	(*ToolSpec)(nil),                   // 5: talon.plugin.v1.ToolSpec
	(*ProviderSpec)(nil),               // 6: talon.plugin.v1.ProviderSpec
	(*ModelDescriptor)(nil),            // 7: talon.plugin.v1.ModelDescriptor
	(*Delta)(nil),                      // 8: talon.plugin.v1.Delta
	(*Usage)(nil),                      // 9: talon.plugin.v1.Usage
	(*InitializeRequest)(nil),          // 10: talon.plugin.v1.InitializeRequest
	(*InitializeResponse)(nil),         // 11: talon.plugin.v1.InitializeResponse
	(*ShutdownRequest)(nil),            // 12: talon.plugin.v1.ShutdownRequest
	(*ShutdownResponse)(nil),           // 13: talon.plugin.v1.ShutdownResponse
	(*RunToolRequest)(nil),             // 14: talon.plugin.v1.RunToolRequest
	(*RunToolResponse)(nil),            // 15: talon.plugin.v1.RunToolResponse
	(*StreamCompletionRequest)(nil),    // 16: talon.plugin.v1.StreamCompletionRequest
	(*ListProviderModelsRequest)(nil),  // 17: talon.plugin.v1.ListProviderModelsRequest
	(*ListProviderModelsResponse)(nil), // 18: talon.plugin.v1.ListProviderModelsResponse
	(*StartChannelRequest)(nil),        // 19: talon.plugin.v1.StartChannelRequest
	(*IncomingChannelMessage)(nil),     // 20: talon.plugin.v1.IncomingChannelMessage
	(*SendChannelMessageRequest)(nil),  // 21: talon.plugin.v1.SendChannelMessageRequest
	(*SendChannelMessageResponse)(nil), // 22: talon.plugin.v1.SendChannelMessageResponse
	(*GetConfigRequest)(nil),           // 23: talon.plugin.v1.GetConfigRequest
	(*GetConfigResponse)(nil),          // 24: talon.plugin.v1.GetConfigResponse
	(*ListAgentsRequest)(nil),          // 25: talon.plugin.v1.ListAgentsRequest
	(*ListAgentsResponse)(nil),         // 26: talon.plugin.v1.ListAgentsResponse
	(*GetAgentIdentityRequest)(nil),    // 27: talon.plugin.v1.GetAgentIdentityRequest
	(*GetAgentIdentityResponse)(nil),   // 28: talon.plugin.v1.GetAgentIdentityResponse
	(*ListModelsRequest)(nil),          // 29: talon.plugin.v1.ListModelsRequest
	(*ListModelsResponse)(nil),         // 30: talon.plugin.v1.ListModelsResponse
	(*ListSessionsRequest)(nil),        // 31: talon.plugin.v1.ListSessionsRequest
	(*ListSessionsResponse)(nil),       // 32: talon.plugin.v1.ListSessionsResponse
	(*GetChatHistoryRequest)(nil),      // 33: talon.plugin.v1.GetChatHistoryRequest
	(*GetChatHistoryResponse)(nil),     // 34: talon.plugin.v1.GetChatHistoryResponse
	(*AppendMemoryRequest)(nil),        // 35: talon.plugin.v1.AppendMemoryRequest
	(*AppendMemoryResponse)(nil),       // 36: talon.plugin.v1.AppendMemoryResponse
	(*RunSubagentRequest)(nil),         // 37: talon.plugin.v1.RunSubagentRequest
	(*RunSubagentResponse)(nil),        // 38: talon.plugin.v1.RunSubagentResponse
}
var file_plugin_proto_depIdxs = []int32{
	5,  // 0: talon.plugin.v1.Manifest.offers_tools:type_name -> talon.plugin.v1.ToolSpec
	6,  // 1: talon.plugin.v1.Manifest.offers_providers:type_name -> talon.plugin.v1.ProviderSpec
	0,  // 2: talon.plugin.v1.Manifest.needs:type_name -> talon.plugin.v1.Capability
	1,  // 3: talon.plugin.v1.Message.role:type_name -> talon.plugin.v1.Role
	4,  // 4: talon.plugin.v1.Message.tool_calls:type_name -> talon.plugin.v1.ToolCall
	9,  // 5: talon.plugin.v1.Delta.usage:type_name -> talon.plugin.v1.Usage
	4,  // 6: talon.plugin.v1.Delta.tool_call:type_name -> talon.plugin.v1.ToolCall
	2,  // 7: talon.plugin.v1.InitializeResponse.manifest:type_name -> talon.plugin.v1.Manifest
	3,  // 8: talon.plugin.v1.StreamCompletionRequest.messages:type_name -> talon.plugin.v1.Message
	5,  // 9: talon.plugin.v1.StreamCompletionRequest.tools:type_name -> talon.plugin.v1.ToolSpec
	7,  // 10: talon.plugin.v1.ListProviderModelsResponse.models:type_name -> talon.plugin.v1.ModelDescriptor
	10, // 11: talon.plugin.v1.Plugin.Initialize:input_type -> talon.plugin.v1.InitializeRequest
	12, // 12: talon.plugin.v1.Plugin.Shutdown:input_type -> talon.plugin.v1.ShutdownRequest
	14, // 13: talon.plugin.v1.Plugin.RunTool:input_type -> talon.plugin.v1.RunToolRequest
	16, // 14: talon.plugin.v1.Plugin.StreamCompletion:input_type -> talon.plugin.v1.StreamCompletionRequest
	17, // 15: talon.plugin.v1.Plugin.ListProviderModels:input_type -> talon.plugin.v1.ListProviderModelsRequest
	19, // 16: talon.plugin.v1.Plugin.StartChannel:input_type -> talon.plugin.v1.StartChannelRequest
	21, // 17: talon.plugin.v1.Plugin.SendChannelMessage:input_type -> talon.plugin.v1.SendChannelMessageRequest
	23, // 18: talon.plugin.v1.Host.GetConfig:input_type -> talon.plugin.v1.GetConfigRequest
	25, // 19: talon.plugin.v1.Host.ListAgents:input_type -> talon.plugin.v1.ListAgentsRequest
	27, // 20: talon.plugin.v1.Host.GetAgentIdentity:input_type -> talon.plugin.v1.GetAgentIdentityRequest
	29, // 21: talon.plugin.v1.Host.ListModels:input_type -> talon.plugin.v1.ListModelsRequest
	31, // 22: talon.plugin.v1.Host.ListSessions:input_type -> talon.plugin.v1.ListSessionsRequest
	33, // 23: talon.plugin.v1.Host.GetChatHistory:input_type -> talon.plugin.v1.GetChatHistoryRequest
	35, // 24: talon.plugin.v1.Host.AppendMemory:input_type -> talon.plugin.v1.AppendMemoryRequest
	37, // 25: talon.plugin.v1.Host.RunSubagent:input_type -> talon.plugin.v1.RunSubagentRequest
	11, // 26: talon.plugin.v1.Plugin.Initialize:output_type -> talon.plugin.v1.InitializeResponse
	13, // 27: talon.plugin.v1.Plugin.Shutdown:output_type -> talon.plugin.v1.ShutdownResponse
	15, // 28: talon.plugin.v1.Plugin.RunTool:output_type -> talon.plugin.v1.RunToolResponse
	8,  // 29: talon.plugin.v1.Plugin.StreamCompletion:output_type -> talon.plugin.v1.Delta
	18, // 30: talon.plugin.v1.Plugin.ListProviderModels:output_type -> talon.plugin.v1.ListProviderModelsResponse
	20, // 31: talon.plugin.v1.Plugin.StartChannel:output_type -> talon.plugin.v1.IncomingChannelMessage
	22, // 32: talon.plugin.v1.Plugin.SendChannelMessage:output_type -> talon.plugin.v1.SendChannelMessageResponse
	24, // 33: talon.plugin.v1.Host.GetConfig:output_type -> talon.plugin.v1.GetConfigResponse
	26, // 34: talon.plugin.v1.Host.ListAgents:output_type -> talon.plugin.v1.ListAgentsResponse
	28, // 35: talon.plugin.v1.Host.GetAgentIdentity:output_type -> talon.plugin.v1.GetAgentIdentityResponse
	30, // 36: talon.plugin.v1.Host.ListModels:output_type -> talon.plugin.v1.ListModelsResponse
	32, // 37: talon.plugin.v1.Host.ListSessions:output_type -> talon.plugin.v1.ListSessionsResponse
	34, // 38: talon.plugin.v1.Host.GetChatHistory:output_type -> talon.plugin.v1.GetChatHistoryResponse
	36, // 39: talon.plugin.v1.Host.AppendMemory:output_type -> talon.plugin.v1.AppendMemoryResponse
	38, // 40: talon.plugin.v1.Host.RunSubagent:output_type -> talon.plugin.v1.RunSubagentResponse
	26, // [26:41] is the sub-list for method output_type
	11, // [11:26] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_plugin_proto_init() }
func file_plugin_proto_init() {
	if File_plugin_proto != nil {
		return
	}
	file_plugin_proto_msgTypes[6].OneofWrappers = []any{
		(*Delta_Text)(nil),
		(*Delta_Reasoning)(nil),
		(*Delta_Usage)(nil),
		(*Delta_ToolCall)(nil),
		(*Delta_Error)(nil),
	}
	file_plugin_proto_msgTypes[14].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_proto_depIdxs,
		EnumInfos:         file_plugin_proto_enumTypes,
		MessageInfos:      file_plugin_proto_msgTypes,
	}.Build()
	File_plugin_proto = out.File
	file_plugin_proto_goTypes = nil
	file_plugin_proto_depIdxs = nil
}
