// talon.plugin.v1 is the wire contract every native plugin implements to
// participate in talon-gateway. Two services:
//
//   service Plugin — host calls these on the plugin (ListTools, RunTool,
//                    StreamCompletion, StartChannel, etc).
//   service Host   — plugin calls these back on the host (GetConfig,
//                    ListAgents, RunSubagent, etc). Every Host method has
//                    an associated Capability the host gates against the
//                    plugin's effective capability set:
//                      effective(plugin, agent) =
//                        manifest.needs ∪ user.grants − user.denies
//
// First-cut goals:
//   - cover the surfaces talon already implements natively (tools,
//     providers, channels-in/out, memory, subagent, identity)
//   - keep capabilities a closed enum so the gating layer is simple
//     reflection over a static map
//   - leave room to add capabilities and methods without breaking
//     existing plugins (proto3 forward-compat)
//
// Out of scope for this proto: subprocess handshake protocol (port +
// auth-cookie negotiation), plugin manifest discovery on disk. Those are
// host-runtime concerns landed in talon-bql.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: plugin.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Plugin_Initialize_FullMethodName         = "/talon.plugin.v1.Plugin/Initialize"
	Plugin_Shutdown_FullMethodName           = "/talon.plugin.v1.Plugin/Shutdown"
	Plugin_RunTool_FullMethodName            = "/talon.plugin.v1.Plugin/RunTool"
	Plugin_StreamCompletion_FullMethodName   = "/talon.plugin.v1.Plugin/StreamCompletion"
	Plugin_ListProviderModels_FullMethodName = "/talon.plugin.v1.Plugin/ListProviderModels"
	Plugin_StartChannel_FullMethodName       = "/talon.plugin.v1.Plugin/StartChannel"
	Plugin_SendChannelMessage_FullMethodName = "/talon.plugin.v1.Plugin/SendChannelMessage"
)

// PluginClient is the client API for Plugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PluginClient interface {
	// Lifecycle. Initialize is the first call after the subprocess
	// handshake completes; the response carries the manifest.
	Initialize(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (*InitializeResponse, error)
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error)
	// Tool capability.
	RunTool(ctx context.Context, in *RunToolRequest, opts ...grpc.CallOption) (*RunToolResponse, error)
	// Provider capability — server-streaming completion deltas.
	StreamCompletion(ctx context.Context, in *StreamCompletionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Delta], error)
	// Provider capability — list the models this provider exposes.
	// Multi-tenant plugins answer per provider name; single-provider
	// plugins ignore the request's provider field. Implementations
	// are encouraged to cache (e.g. 5min TTL) to keep models.list
	// cheap. If unsupported, return UNIMPLEMENTED and the host falls
	// back to the manifest's static model list.
	ListProviderModels(ctx context.Context, in *ListProviderModelsRequest, opts ...grpc.CallOption) (*ListProviderModelsResponse, error)
	// Channel capability. StartChannel returns a server-stream of inbound
	// messages from the channel (Telegram polling, Slack events, etc.).
	// SendChannelMessage is the outbound side; idempotency is the
	// plugin's responsibility.
	StartChannel(ctx context.Context, in *StartChannelRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[IncomingChannelMessage], error)
	SendChannelMessage(ctx context.Context, in *SendChannelMessageRequest, opts ...grpc.CallOption) (*SendChannelMessageResponse, error)
}

type pluginClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginClient(cc grpc.ClientConnInterface) PluginClient {
	return &pluginClient{cc}
}

func (c *pluginClient) Initialize(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (*InitializeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitializeResponse)
	err := c.cc.Invoke(ctx, Plugin_Initialize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShutdownResponse)
	err := c.cc.Invoke(ctx, Plugin_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) RunTool(ctx context.Context, in *RunToolRequest, opts ...grpc.CallOption) (*RunToolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunToolResponse)
	err := c.cc.Invoke(ctx, Plugin_RunTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) StreamCompletion(ctx context.Context, in *StreamCompletionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Delta], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Plugin_ServiceDesc.Streams[0], Plugin_StreamCompletion_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamCompletionRequest, Delta]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Plugin_StreamCompletionClient = grpc.ServerStreamingClient[Delta]

func (c *pluginClient) ListProviderModels(ctx context.Context, in *ListProviderModelsRequest, opts ...grpc.CallOption) (*ListProviderModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProviderModelsResponse)
	err := c.cc.Invoke(ctx, Plugin_ListProviderModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) StartChannel(ctx context.Context, in *StartChannelRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[IncomingChannelMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Plugin_ServiceDesc.Streams[1], Plugin_StartChannel_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StartChannelRequest, IncomingChannelMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Plugin_StartChannelClient = grpc.ServerStreamingClient[IncomingChannelMessage]

func (c *pluginClient) SendChannelMessage(ctx context.Context, in *SendChannelMessageRequest, opts ...grpc.CallOption) (*SendChannelMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendChannelMessageResponse)
	err := c.cc.Invoke(ctx, Plugin_SendChannelMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginServer is the server API for Plugin service.
// All implementations must embed UnimplementedPluginServer
// for forward compatibility.
type PluginServer interface {
	// Lifecycle. Initialize is the first call after the subprocess
	// handshake completes; the response carries the manifest.
	Initialize(context.Context, *InitializeRequest) (*InitializeResponse, error)
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error)
	// Tool capability.
	RunTool(context.Context, *RunToolRequest) (*RunToolResponse, error)
	// Provider capability — server-streaming completion deltas.
	StreamCompletion(*StreamCompletionRequest, grpc.ServerStreamingServer[Delta]) error
	// Provider capability — list the models this provider exposes.
	// Multi-tenant plugins answer per provider name; single-provider
	// plugins ignore the request's provider field. Implementations
	// are encouraged to cache (e.g. 5min TTL) to keep models.list
	// cheap. If unsupported, return UNIMPLEMENTED and the host falls
	// back to the manifest's static model list.
	ListProviderModels(context.Context, *ListProviderModelsRequest) (*ListProviderModelsResponse, error)
	// Channel capability. StartChannel returns a server-stream of inbound
	// messages from the channel (Telegram polling, Slack events, etc.).
	// SendChannelMessage is the outbound side; idempotency is the
	// plugin's responsibility.
	StartChannel(*StartChannelRequest, grpc.ServerStreamingServer[IncomingChannelMessage]) error
	SendChannelMessage(context.Context, *SendChannelMessageRequest) (*SendChannelMessageResponse, error)
	mustEmbedUnimplementedPluginServer()
}

// UnimplementedPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginServer struct{}

func (UnimplementedPluginServer) Initialize(context.Context, *InitializeRequest) (*InitializeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Initialize not implemented")
}
func (UnimplementedPluginServer) Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedPluginServer) RunTool(context.Context, *RunToolRequest) (*RunToolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunTool not implemented")
}
func (UnimplementedPluginServer) StreamCompletion(*StreamCompletionRequest, grpc.ServerStreamingServer[Delta]) error {
	return status.Error(codes.Unimplemented, "method StreamCompletion not implemented")
}
func (UnimplementedPluginServer) ListProviderModels(context.Context, *ListProviderModelsRequest) (*ListProviderModelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProviderModels not implemented")
}
func (UnimplementedPluginServer) StartChannel(*StartChannelRequest, grpc.ServerStreamingServer[IncomingChannelMessage]) error {
	return status.Error(codes.Unimplemented, "method StartChannel not implemented")
}
func (UnimplementedPluginServer) SendChannelMessage(context.Context, *SendChannelMessageRequest) (*SendChannelMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendChannelMessage not implemented")
}
func (UnimplementedPluginServer) mustEmbedUnimplementedPluginServer() {}
func (UnimplementedPluginServer) testEmbeddedByValue()                {}

// UnsafePluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginServer will
// result in compilation errors.
type UnsafePluginServer interface {
	mustEmbedUnimplementedPluginServer()
}

func RegisterPluginServer(s grpc.ServiceRegistrar, srv PluginServer) {
	// If the following call panics, it indicates UnimplementedPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Plugin_ServiceDesc, srv)
}

func _Plugin_Initialize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitializeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).Initialize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_Initialize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).Initialize(ctx, req.(*InitializeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_RunTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).RunTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_RunTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).RunTool(ctx, req.(*RunToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_StreamCompletion_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamCompletionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PluginServer).StreamCompletion(m, &grpc.GenericServerStream[StreamCompletionRequest, Delta]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Plugin_StreamCompletionServer = grpc.ServerStreamingServer[Delta]

func _Plugin_ListProviderModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProviderModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).ListProviderModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_ListProviderModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).ListProviderModels(ctx, req.(*ListProviderModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_StartChannel_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StartChannelRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PluginServer).StartChannel(m, &grpc.GenericServerStream[StartChannelRequest, IncomingChannelMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Plugin_StartChannelServer = grpc.ServerStreamingServer[IncomingChannelMessage]

func _Plugin_SendChannelMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendChannelMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).SendChannelMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_SendChannelMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).SendChannelMessage(ctx, req.(*SendChannelMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Plugin_ServiceDesc is the grpc.ServiceDesc for Plugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Plugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "talon.plugin.v1.Plugin",
	HandlerType: (*PluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Initialize",
			Handler:    _Plugin_Initialize_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _Plugin_Shutdown_Handler,
		},
		{
			MethodName: "RunTool",
			Handler:    _Plugin_RunTool_Handler,
		},
		{
			MethodName: "ListProviderModels",
			Handler:    _Plugin_ListProviderModels_Handler,
		},
		{
			MethodName: "SendChannelMessage",
			Handler:    _Plugin_SendChannelMessage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamCompletion",
			Handler:       _Plugin_StreamCompletion_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StartChannel",
			Handler:       _Plugin_StartChannel_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "plugin.proto",
}

const (
	Host_GetConfig_FullMethodName        = "/talon.plugin.v1.Host/GetConfig"
	Host_ListAgents_FullMethodName       = "/talon.plugin.v1.Host/ListAgents"
	Host_GetAgentIdentity_FullMethodName = "/talon.plugin.v1.Host/GetAgentIdentity"
	Host_ListModels_FullMethodName       = "/talon.plugin.v1.Host/ListModels"
	Host_ListSessions_FullMethodName     = "/talon.plugin.v1.Host/ListSessions"
	Host_GetChatHistory_FullMethodName   = "/talon.plugin.v1.Host/GetChatHistory"
	Host_AppendMemory_FullMethodName     = "/talon.plugin.v1.Host/AppendMemory"
	Host_RunSubagent_FullMethodName      = "/talon.plugin.v1.Host/RunSubagent"
)

// HostClient is the client API for Host service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HostClient interface {
	// CAPABILITY_READ_CONFIG
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error)
	// CAPABILITY_LIST_AGENTS
	ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error)
	// CAPABILITY_READ_AGENT_IDENTITY
	GetAgentIdentity(ctx context.Context, in *GetAgentIdentityRequest, opts ...grpc.CallOption) (*GetAgentIdentityResponse, error)
	// CAPABILITY_LIST_MODELS
	ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error)
	// CAPABILITY_LIST_SESSIONS
	ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error)
	// CAPABILITY_READ_CHAT_HISTORY
	GetChatHistory(ctx context.Context, in *GetChatHistoryRequest, opts ...grpc.CallOption) (*GetChatHistoryResponse, error)
	// CAPABILITY_APPEND_MEMORY
	AppendMemory(ctx context.Context, in *AppendMemoryRequest, opts ...grpc.CallOption) (*AppendMemoryResponse, error)
	// CAPABILITY_RUN_SUBAGENT
	RunSubagent(ctx context.Context, in *RunSubagentRequest, opts ...grpc.CallOption) (*RunSubagentResponse, error)
}

type hostClient struct {
	cc grpc.ClientConnInterface
}

func NewHostClient(cc grpc.ClientConnInterface) HostClient {
	return &hostClient{cc}
}

func (c *hostClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConfigResponse)
	err := c.cc.Invoke(ctx, Host_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAgentsResponse)
	err := c.cc.Invoke(ctx, Host_ListAgents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) GetAgentIdentity(ctx context.Context, in *GetAgentIdentityRequest, opts ...grpc.CallOption) (*GetAgentIdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAgentIdentityResponse)
	err := c.cc.Invoke(ctx, Host_GetAgentIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModelsResponse)
	err := c.cc.Invoke(ctx, Host_ListModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsResponse)
	err := c.cc.Invoke(ctx, Host_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) GetChatHistory(ctx context.Context, in *GetChatHistoryRequest, opts ...grpc.CallOption) (*GetChatHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChatHistoryResponse)
	err := c.cc.Invoke(ctx, Host_GetChatHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) AppendMemory(ctx context.Context, in *AppendMemoryRequest, opts ...grpc.CallOption) (*AppendMemoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppendMemoryResponse)
	err := c.cc.Invoke(ctx, Host_AppendMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostClient) RunSubagent(ctx context.Context, in *RunSubagentRequest, opts ...grpc.CallOption) (*RunSubagentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunSubagentResponse)
	err := c.cc.Invoke(ctx, Host_RunSubagent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HostServer is the server API for Host service.
// All implementations must embed UnimplementedHostServer
// for forward compatibility.
type HostServer interface {
	// CAPABILITY_READ_CONFIG
	GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error)
	// CAPABILITY_LIST_AGENTS
	ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsResponse, error)
	// CAPABILITY_READ_AGENT_IDENTITY
	GetAgentIdentity(context.Context, *GetAgentIdentityRequest) (*GetAgentIdentityResponse, error)
	// CAPABILITY_LIST_MODELS
	ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error)
	// CAPABILITY_LIST_SESSIONS
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error)
	// CAPABILITY_READ_CHAT_HISTORY
	GetChatHistory(context.Context, *GetChatHistoryRequest) (*GetChatHistoryResponse, error)
	// CAPABILITY_APPEND_MEMORY
	AppendMemory(context.Context, *AppendMemoryRequest) (*AppendMemoryResponse, error)
	// CAPABILITY_RUN_SUBAGENT
	RunSubagent(context.Context, *RunSubagentRequest) (*RunSubagentResponse, error)
	mustEmbedUnimplementedHostServer()
}

// UnimplementedHostServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHostServer struct{}

func (UnimplementedHostServer) GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedHostServer) ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAgents not implemented")
}
func (UnimplementedHostServer) GetAgentIdentity(context.Context, *GetAgentIdentityRequest) (*GetAgentIdentityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAgentIdentity not implemented")
}
func (UnimplementedHostServer) ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedHostServer) ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedHostServer) GetChatHistory(context.Context, *GetChatHistoryRequest) (*GetChatHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChatHistory not implemented")
}
func (UnimplementedHostServer) AppendMemory(context.Context, *AppendMemoryRequest) (*AppendMemoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AppendMemory not implemented")
}
func (UnimplementedHostServer) RunSubagent(context.Context, *RunSubagentRequest) (*RunSubagentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunSubagent not implemented")
}
func (UnimplementedHostServer) mustEmbedUnimplementedHostServer() {}
func (UnimplementedHostServer) testEmbeddedByValue()              {}

// UnsafeHostServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HostServer will
// result in compilation errors.
type UnsafeHostServer interface {
	mustEmbedUnimplementedHostServer()
}

func RegisterHostServer(s grpc.ServiceRegistrar, srv HostServer) {
	// If the following call panics, it indicates UnimplementedHostServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Host_ServiceDesc, srv)
}

func _Host_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_ListAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).ListAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_ListAgents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).ListAgents(ctx, req.(*ListAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_GetAgentIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).GetAgentIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_GetAgentIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).GetAgentIdentity(ctx, req.(*GetAgentIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_ListModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).ListModels(ctx, req.(*ListModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).ListSessions(ctx, req.(*ListSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_GetChatHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChatHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).GetChatHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_GetChatHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).GetChatHistory(ctx, req.(*GetChatHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_AppendMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendMemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).AppendMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_AppendMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).AppendMemory(ctx, req.(*AppendMemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Host_RunSubagent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunSubagentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServer).RunSubagent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Host_RunSubagent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServer).RunSubagent(ctx, req.(*RunSubagentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Host_ServiceDesc is the grpc.ServiceDesc for Host service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Host_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "talon.plugin.v1.Host",
	HandlerType: (*HostServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConfig",
			Handler:    _Host_GetConfig_Handler,
		},
		{
			MethodName: "ListAgents",
			Handler:    _Host_ListAgents_Handler,
		},
		{
			MethodName: "GetAgentIdentity",
			Handler:    _Host_GetAgentIdentity_Handler,
		},
		{
			MethodName: "ListModels",
			Handler:    _Host_ListModels_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _Host_ListSessions_Handler,
		},
		{
			MethodName: "GetChatHistory",
			Handler:    _Host_GetChatHistory_Handler,
		},
		{
			MethodName: "AppendMemory",
			Handler:    _Host_AppendMemory_Handler,
		},
		{
			MethodName: "RunSubagent",
			Handler:    _Host_RunSubagent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}
