import { a as coerceSecretRef } from "../../types.secrets-jH4K3BIC.js";
import { n as ensureAuthProfileStore } from "../../store-C_AygAy6.js";
import { n as listProfilesForProvider } from "../../profile-list-Cub4ft7g.js";
import "../../provider-auth-FLKju3Cq.js";
import { r as resolveCopilotApiToken, t as DEFAULT_COPILOT_API_BASE_URL } from "../../github-copilot-token-96jjoyT6.js";
import { t as githubCopilotLoginCommand } from "../../provider-auth-login-VEI02rFz.js";
import { n as resolveCopilotForwardCompatModel, t as PROVIDER_ID } from "../../models-BLhr07Fh.js";
import { r as wrapCopilotProviderStream, t as wrapCopilotAnthropicStream } from "../../stream-6K1V-oaj.js";
import "../../token-o7gQgD7F.js";
import { t as fetchCopilotUsage } from "../../usage-CTM70Ikq.js";
export { DEFAULT_COPILOT_API_BASE_URL, PROVIDER_ID, coerceSecretRef, ensureAuthProfileStore, fetchCopilotUsage, githubCopilotLoginCommand, listProfilesForProvider, resolveCopilotApiToken, resolveCopilotForwardCompatModel, wrapCopilotAnthropicStream, wrapCopilotProviderStream };
